(in-package #:cl-yaml-kit/test)

(defun directive-tokens (text)
  (let ((s (yaml-kit:make-scanner (make-array (length text) :element-type 'character
                                               :initial-contents text))) (out nil))
    (loop for token = (yaml-kit:scanner-next-token s) while token do (push token out))
    (nreverse out)))

(defmacro scanner-directive-cases (&body cases)
  `(progn ,@(mapcar (lambda (case)
                      `(it ,(first case)
                         (let ((actual (remove-if (lambda (token)
                                                    (member (yaml-kit:token-kind token)
                                                            '(:stream-start :stream-end)))
                                                  (directive-tokens ,(second case)))))
                           (expect (mapcar (lambda (token)
                                             (list (yaml-kit:token-kind token)
                                                   (yaml-kit:token-value token)
                                                   (yaml-kit:token-handle token)
                                                   (yaml-kit:token-suffix token)
                                                   (yaml-kit:token-major token)
                                                   (yaml-kit:token-minor token))) actual)
                                   :to-equal ',(third case))))) cases)))

(scanner-directive-cases
  ("YAML version" (format nil "%YAML 1.2~%") ((:version-directive nil nil nil 1 2)))
  ("reserved directive 6LVF" (format nil "%FOO  bar baz # Should be ignored~%--- \"foo\"~%")
   ((:document-start nil nil nil nil nil) (:scalar "foo" nil nil nil nil)))
  ("reserved directive 2LFX" (format nil "%FOO  bar baz # Should be ignored~%---~%\"foo\"~%")
   ((:document-start nil nil nil nil nil) (:scalar "foo" nil nil nil nil)))
  ("TAG directive" (format nil "%TAG !e! tag:example.com,2000:~%")
   ((:tag-directive "tag:example.com,2000:" "!e!" nil nil nil)))
  ("TAG handle and suffix" (format nil "%TAG !e! tag:example.com,2000:~%--- !e!foo~%")
   ((:tag-directive "tag:example.com,2000:" "!e!" nil nil nil)
    (:document-start nil nil nil nil nil)
    (:tag nil "!e!" "foo" nil nil)))
  ("verbatim tag keeps trailing bang" (format nil "!<tag:yaml.org,2002:str!> value~%")
   ((:tag nil "" "tag:yaml.org,2002:str!" nil nil)
    (:scalar "value" nil nil nil nil)))
  ("anchors and aliases" (format nil "&a *a~%")
   ((:anchor "a" nil nil nil nil) (:alias "a" nil nil nil nil)))
  ("8XYN unicode anchor" (format nil "--- &😁 unicode anchor~%")
   ((:document-start nil nil nil nil nil)
    (:anchor "😁" nil nil nil nil) (:scalar "unicode anchor" nil nil nil nil)))
  ("anchor accepts non-flow punctuation" (format nil "&a! value~%")
   ((:anchor "a!" nil nil nil nil) (:scalar "value" nil nil nil nil)))
  ;; ns-anchor-char excludes only c-flow-indicator, so ":" stays in the name
  ;; and the line is an anchored scalar rather than a mapping.
  ("anchor keeps a trailing colon" (format nil "&a: value~%")
   ((:anchor "a:" nil nil nil nil) (:scalar "value" nil nil nil nil)))
  ("tag forms" (format nil "! !!str !e!foo !<tag:yaml.org,2002:str>~%")
   ((:tag nil "" "!" nil nil) (:tag nil "!!" "str" nil nil)
    (:tag nil "!e!" "foo" nil nil) (:tag nil "" "tag:yaml.org,2002:str" nil nil)))
  ("URI escape" (format nil "!%21~%") ((:tag nil "!" "!" nil nil)))
  ("URI escape UTF-8" (format nil "!%C3%A9%20%E2%82%AC%20%F0%9F%98%81~%")
   ((:tag nil "!" "é € 😁" nil nil)))
)

(defmacro scanner-directive-errors (&body cases)
  `(progn ,@(mapcar (lambda (case)
                      `(it ,(first case)
                         (let ((raised nil))
                           (handler-case (directive-tokens ,(second case))
                             (yaml-kit:yaml-parse-error () (setf raised t)))
                           (expect raised :to-be-truthy)))) cases)))

(scanner-directive-errors
  ("invalid version" (format nil "%YAML 2.0~%"))
  ("incomplete version" (format nil "%YAML 1.~%"))
  ("unterminated verbatim tag" (format nil "!<tag:yaml.org,2002:str~%"))
  ("empty anchor" (format nil "&~%"))
  ("empty alias" (format nil "*~%"))
  ("flow indicator in anchor" (format nil "&a, value~%"))
  ("flow indicator in alias" (format nil "*a,~%"))
  ("URI escape overlong UTF-8" (format nil "!%C0%80~%"))
  ("URI escape surrogate UTF-8" (format nil "!%ED%A0%80~%"))
  ("URI escape out-of-range UTF-8" (format nil "!%F4%90%80%80~%"))
  ("URI escape truncated UTF-8" (format nil "!%E2%82~%")))
