;; Category data. The checker reads source forms and derives line spans.
(:kind top-level-form :head "in-package" :reason "SB-COVER records the compile-time package form as not executed." :reproduction "scripts/coverage-reproductions/in-package.lisp")
(:kind top-level-form :head "defpackage" :reason "Package definitions are compile/load-time metadata without a runtime location." :reproduction "scripts/coverage-reproductions/in-package.lisp")
(:kind top-level-form :head "declaim" :reason "SB-COVER records declarations, including inline declarations, as not executed." :reproduction "scripts/coverage-reproductions/declaim.lisp")
(:kind top-level-form :head "defconstant" :reason "Constant initialization is performed while compiling/loading the form." :reproduction "scripts/coverage-reproductions/defconstant.lisp")
(:kind top-level-form :head "defparameter" :reason "Top-level variable initialization is performed while loading the file." :reproduction "scripts/coverage-reproductions/defconstant.lisp")
(:kind top-level-form :head "defvar" :reason "Top-level variable declaration has no independently executable coverage location." :reproduction "scripts/coverage-reproductions/defconstant.lisp")
(:kind top-level-form :head "define-condition" :reason "Condition class metadata is expanded during compilation." :reproduction "scripts/coverage-reproductions/defstruct.lisp")
(:kind top-level-form :head "defstruct" :reason "DEFSTRUCT slot declarations are expanded at compile time and have no runtime location." :reproduction "scripts/coverage-reproductions/defstruct.lisp")
(:kind top-level-form :head "define-node" :reason "DEFINE-NODE expands structure metadata at compile time." :reproduction "scripts/coverage-reproductions/defstruct.lisp")
(:kind top-level-form :head "deftype" :reason "Type definitions are compile-time declarations without runtime locations." :reproduction "scripts/coverage-reproductions/defconstant.lisp")
(:kind top-level-form :head "eval-when" :reason "Compile/load-time macro expansion has no independent runtime coverage location." :reproduction "scripts/coverage-reproductions/defstruct.lisp")
(:kind top-level-form :head "define-yaml-subtype" :reason "The subtype macro expands structure metadata at compile time." :reproduction "scripts/coverage-reproductions/defstruct.lisp")
(:kind top-level-form :head "define-event" :reason "Event declarations expand into structure metadata at compile time." :reproduction "scripts/coverage-reproductions/defstruct.lisp")
(:kind top-level-form :head "define-tag-table" :reason "The tag table macro expands static data at compile time." :reproduction "scripts/coverage-reproductions/defconstant.lisp")
(:kind handler-clause :head "handler-case" :reason "SB-COVER does not attach an executable location to handler clause syntax." :reproduction "scripts/coverage-reproductions/handler-case.lisp")
(:kind defun-header :head "defun" :reason "SB-COVER marks the DEFUN header and lambda list, not an executable expression." :reproduction "scripts/coverage-reproductions/defun-header.lisp")
(:kind defun-header :head "defmacro" :reason "Macro headers are consumed during compilation and do not execute at runtime." :reproduction "scripts/coverage-reproductions/defun-header.lisp")
