;;;; Measure per-file line and branch coverage of a full cl-yaml-kit test run.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require :asdf)
  (require :sb-cover))

(defparameter *default-output-directory* "/tmp/cl-yaml-kit-coverage/")

(defparameter *default-source-directory* "src/")

(defparameter *summary-comment*
  '("# cl-yaml-kit per-file coverage summary"
    "# generated by scripts/run-coverage.lisp from a full test-suite run"))

(defparameter *summary-columns*
  '("file" "line-covered" "line-total" "branch-covered" "branch-total"
    "uncovered-lines"))

(defun checkout-root ()
  (let ((script (or *load-truename* *compile-file-truename*
                    (error "Unable to determine the coverage script location"))))
    (uiop:pathname-parent-directory-pathname
     (uiop:pathname-directory-pathname script))))

(defun environment-path (variable fallback)
  (pathname (or (uiop:getenv variable)
                (merge-pathnames fallback *default-output-directory*))))

(defun sb-cover-symbol (name)
  (multiple-value-bind (symbol status)
      (find-symbol name (or (find-package "SB-COVER")
                           (error "SB-COVER is not loaded; cannot measure coverage.")))
    (or (and status symbol)
        (error "SB-COVER ~A is not available in SBCL ~A."
               name (lisp-implementation-version)))))

(defun sb-cover-function (name)
  (let ((symbol (sb-cover-symbol name)))
    (or (and (fboundp symbol) symbol)
        (error "SB-COVER ~A has no function definition in SBCL ~A."
               name (lisp-implementation-version)))))

(defun sb-cover-value (name)
  (let ((symbol (sb-cover-symbol name)))
    (or (boundp symbol)
        (error "SB-COVER ~A is unbound in SBCL ~A."
               name (lisp-implementation-version)))
    (symbol-value symbol)))

(defun coverage-source-table ()
  (let ((value (sb-cover-value "*CODE-COVERAGE-INFO*")))
    (unless (and (consp value) (hash-table-p (car value)))
      (error "SB-COVER coverage data has an unsupported representation."))
    (car value)))

(defun resolve-source-directory (root)
  (merge-pathnames (uiop:ensure-directory-pathname
                    (pathname (or (uiop:getenv "COVERAGE_SOURCE_DIRECTORY")
                                  *default-source-directory*)))
                   root))

(defun source-lisp-files (source-directory)
  (sort (directory (merge-pathnames "*.lisp" source-directory)
                   :resolve-symlinks t)
        #'string<
        :key #'file-namestring))

(defun require-coverage-entries (table files)
  (let ((missing (remove-if (lambda (file)
                              (nth-value 1 (gethash (namestring file) table)))
                            files)))
    (when missing
      (error "SB-COVER recorded no coverage for ~{~A~^, ~}; the per-file summary would be short."
             (mapcar #'file-namestring missing)))))

(defun line-execution-state (states start end)
  "0 when the feasible states of a line include a not-executed one, 1 when
every feasible state was executed, NIL when the line holds only ignored states.
Mirrors SB-COVER::SUMMARIZE-STATES-BETWEEN so these per-line verdicts agree
with the DA: records SB-COVER writes itself."
  (let ((executed nil) (not-executed nil))
    (loop for index from start below end
          do (ecase (aref states index)
               ((0 15))
               ((2 10) (setf not-executed t))
               ((1 5 6 9) (setf executed t))))
    (cond (not-executed 0)
          (executed 1))))

(defun uncovered-line-numbers (states linelengths)
  (let ((state-index 0) (line 1) (uncovered nil))
    (loop
      (let ((line-length (aref linelengths (1- line))))
        (when (eql 0 (line-execution-state states state-index
                                           (+ state-index line-length)))
          (push line uncovered))
        (when (>= (incf state-index (1+ line-length)) (length states))
          (return (nreverse uncovered))))
      (incf line))))

(defun compress-line-ranges (lines)
  (let ((runs nil) (start nil) (previous nil))
    (flet ((emit-run ()
             (when start
               (push (if (= start previous)
                         (princ-to-string start)
                         (format nil "~D-~D" start previous))
                     runs))))
      (dolist (line lines (progn (emit-run) (format nil "~{~A~^,~}" (nreverse runs))))
        (cond ((null start) (setf start line previous line))
              ((= line (1+ previous)) (setf previous line))
              (t (emit-run) (setf start line previous line)))))))

(defun sample-counts (counts kind)
  (let ((sample (getf counts kind)))
    (values (funcall (sb-cover-function "OK-OF") sample)
            (funcall (sb-cover-function "ALL-OF") sample))))

(defun source-coverage-row (file)
  (multiple-value-bind (counts states linelengths)
      (funcall (sb-cover-function "COMPUTE-FILE-STATES") (namestring file))
    (if (null counts)
        (list (file-namestring file) 0 0 0 0 "-")
        (multiple-value-bind (line-covered line-total) (sample-counts counts :expression)
          (multiple-value-bind (branch-covered branch-total) (sample-counts counts :branch)
            (list (file-namestring file) line-covered line-total branch-covered branch-total
                  (or (compress-line-ranges (uncovered-line-numbers states linelengths))
                      "-")))))))

(defun tab-separated (columns)
  (with-output-to-string (stream)
    (loop for remaining on columns
          while remaining
          do (princ (first remaining) stream)
             (when (rest remaining) (write-char #\Tab stream)))))

(defun write-summary (pathname rows)
  (ensure-directories-exist pathname)
  ;; FORMAT-CONTROL NIL pins the line terminator to LF; the default is CRLF on
  ;; Windows, and the summary is a byte-level interchange file.
  (let ((format-control nil))
    (with-open-file (stream pathname :direction :output
                                 :if-exists :supersede
                                 :if-does-not-exist :create
                                 :external-format :utf-8)
      (flet ((write-row (columns)
               (write-line (tab-separated columns) stream)))
        (dolist (line *summary-comment*)
          (write-line line stream))
        (write-row *summary-columns*)
        (dolist (row rows)
          (write-row row))))))

(defun write-html-report (directory source-directory)
  (ensure-directories-exist directory)
  (let ((prefix (namestring source-directory)))
    (sb-cover:report directory :if-matches (lambda (source)
                                             (uiop:string-prefix-p prefix source)))))

(defun ensure-output-directories (data-file report-directory summary-file)
  (dolist (pathname (list (uiop:pathname-parent-directory-pathname data-file)
                          (uiop:ensure-directory-pathname report-directory)
                          (uiop:pathname-parent-directory-pathname summary-file)))
    (ensure-directories-exist pathname)))

(let* ((root (checkout-root))
       (source-directory (resolve-source-directory root))
       (data-file (environment-path "COVERAGE_OUTPUT" "cl-yaml-kit.coverage"))
       (report-directory (environment-path "COVERAGE_REPORT_DIRECTORY" "report/"))
       (summary-file (environment-path "COVERAGE_SUMMARY" "per-file.tsv")))
  (uiop:chdir root)
  ;; The conformance stages are driven from the single suite entry point, so a
  ;; missing fixture would silently skip them.
  (unless (uiop:getenv "YAML_TEST_SUITE")
    (error "YAML_TEST_SUITE must name the yaml-test-suite fixture directory."))
  (ensure-output-directories data-file report-directory summary-file)
  (proclaim '(optimize (sb-cover:store-coverage-data 3)))
  (asdf:load-asd (merge-pathnames "cl-yaml-kit.asd" root))
  ;; COVERAGE-AUGMENTATION-HOOK must be armed before anything is compiled:
  ;; without it SB-COVER stores no per-line locations and COMPUTE-FILE-STATES
  ;; reports every file as unmeasured.
  (sb-cover:enable-coverage-logging)
  (asdf:operate 'asdf:compile-op "cl-yaml-kit" :force t)
  (asdf:operate 'asdf:compile-op "cl-yaml-kit/test" :force t)
  (asdf:load-system "cl-yaml-kit/test")
  ;; RESET-COVERAGE must follow the loads: it discards the coverage recorded
  ;; while the systems were compiled and loaded so only the suite counts.
  (sb-cover:reset-coverage)
  ;; The report must survive a failed suite, and cl-weave can abort the process
  ;; with a control-stack overflow while pretty-printing a failure, so the
  ;; artifacts are written from the cleanup rather than after the test run.
  (let ((passed nil))
    (unwind-protect
         (setf passed (handler-case (uiop:symbol-call :cl-yaml-kit/test :run-tests)
                        (serious-condition (condition)
                          (format *error-output*
                                  "~&cl-yaml-kit test run failed: ~A~%" condition)
                          nil)))
      (funcall (sb-cover-function "REFRESH-COVERAGE-BITS"))
      (let ((table (coverage-source-table))
            (files (source-lisp-files source-directory)))
        (unless files
          (error "No *.lisp files under ~A." (namestring source-directory)))
        (require-coverage-entries table files)
        (let ((rows (mapcar #'source-coverage-row files)))
          ;; A full suite run must execute something. Zero covered expressions
          ;; means the loaded code carried no coverage marks, which happens when
          ;; another process replaced the compiled output between the compile and
          ;; the load; reporting it as 0% would be a measurement artefact.
          (when (zerop (loop for row in rows sum (second row)))
            (error "No covered expressions under ~A; the loaded code was not instrumented."
                   (namestring source-directory)))
          (sb-cover:save-coverage-in-file data-file)
          (write-html-report report-directory source-directory)
          (write-summary summary-file rows)
          (format t "~&Wrote ~D per-file coverage rows to ~A.~%"
                  (length rows) (namestring summary-file)))))
    (uiop:quit (if passed 0 1))))
