;;;; Measure cl-yaml-kit coverage through cl-weave's coverage API.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require :asdf)
  (require :sb-cover))

(defparameter *default-output-directory* "/tmp/cl-yaml-kit-coverage/")
(defparameter *default-source-directory* "src/")
(defparameter *default-cache-directory* "asdf-cache/")
(defparameter *summary-comment*
  '("# cl-yaml-kit per-file coverage summary"
    "# generated by scripts/run-coverage.lisp from a full test-suite run"))
(defparameter *summary-columns*
  '("file" "line-covered" "line-total" "branch-covered" "branch-total"
    "uncovered-lines"))

(defun checkout-root ()
  (let ((script (or *load-truename* *compile-file-truename*
                    (error "Unable to determine the coverage script location"))))
    (uiop:pathname-parent-directory-pathname
     (uiop:pathname-directory-pathname script))))

(defun environment-path (variable fallback)
  (pathname (or (uiop:getenv variable)
                (merge-pathnames fallback *default-output-directory*))))

(defun sb-cover-symbol (name)
  (multiple-value-bind (symbol status)
      (find-symbol name (or (find-package "SB-COVER")
                            (error "SB-COVER is not loaded; cannot measure coverage.")))
    (or (and status symbol)
        (error "SB-COVER ~A is not available in SBCL ~A."
               name (lisp-implementation-version)))))

(defun sb-cover-function (name)
  (let ((symbol (sb-cover-symbol name)))
    (or (and (fboundp symbol) symbol)
        (error "SB-COVER ~A has no function definition in SBCL ~A."
               name (lisp-implementation-version)))))

(defun resolve-source-directory (root)
  (merge-pathnames (uiop:ensure-directory-pathname
                    (pathname (or (uiop:getenv "COVERAGE_SOURCE_DIRECTORY")
                                  *default-source-directory*)))
                   root))

(defun source-lisp-files (source-directory)
  (sort (directory (merge-pathnames "*.lisp" source-directory)
                   :resolve-symlinks t)
        #'string< :key #'file-namestring))

(defun coverage-source-table ()
  (let ((value (symbol-value (sb-cover-symbol "*CODE-COVERAGE-INFO*"))))
    (unless (and (consp value) (hash-table-p (car value)))
      (error "SB-COVER coverage data has an unsupported representation."))
    (car value)))

(defun require-coverage-entries (table files)
  (let ((missing (remove-if (lambda (file)
                              (nth-value 1 (gethash (namestring file) table)))
                            files)))
    (when missing
      (error "SB-COVER recorded no coverage for ~{~A~^, ~}; the per-file summary would be short."
             (mapcar #'file-namestring missing)))))

(defun line-execution-state (states start end)
  (let ((executed nil) (not-executed nil))
    (loop for index from start below end
          do (ecase (aref states index)
               ((0 15))
               ((2 10) (setf not-executed t))
               ((1 5 6 9) (setf executed t))))
    (cond (not-executed 0) (executed 1))))

(defun uncovered-line-numbers (states linelengths)
  (let ((state-index 0) (line 1) (uncovered nil))
    (loop
      (let ((line-length (aref linelengths (1- line))))
        (when (eql 0 (line-execution-state states state-index
                                           (+ state-index line-length)))
          (push line uncovered))
        (when (>= (incf state-index (1+ line-length)) (length states))
          (return (nreverse uncovered))))
      (incf line))))

(defun compress-line-ranges (lines)
  (let ((runs nil) (start nil) (previous nil))
    (flet ((emit-run ()
             (when start
               (push (if (= start previous)
                         (princ-to-string start)
                         (format nil "~D-~D" start previous))
                     runs))))
      (dolist (line lines (progn (emit-run) (format nil "~{~A~^,~}" (nreverse runs))))
        (cond ((null start) (setf start line previous line))
              ((= line (1+ previous)) (setf previous line))
              (t (emit-run) (setf start line previous line)))))))

(defun source-line-lengths (source)
  (let ((lengths nil)
        (start 0))
    (loop for end = (position #\Newline source :start start)
          do (push (- (or end (length source)) start) lengths)
             (if end
                 (setf start (1+ end))
                 (return (coerce (nreverse lengths) 'vector))))))

(defun sample-counts (counts kind)
  (values (funcall (sb-cover-function "OK-OF") (getf counts kind))
          (funcall (sb-cover-function "ALL-OF") (getf counts kind))))

(defun source-coverage-row (file)
  (multiple-value-bind (counts states source)
      (funcall (sb-cover-function "COMPUTE-FILE-INFO")
               (namestring file) :default)
    (if (null counts)
        (list (file-namestring file) 0 0 0 0 "-")
        (multiple-value-bind (line-covered line-total) (sample-counts counts :expression)
          (multiple-value-bind (branch-covered branch-total) (sample-counts counts :branch)
            (list (file-namestring file) line-covered line-total branch-covered branch-total
                  (or (and states source
                           (compress-line-ranges
                            (uncovered-line-numbers states (source-line-lengths source))))
                      "-")))))))

(defun tab-separated (columns)
  (with-output-to-string (stream)
    (loop for remaining on columns
          while remaining
          do (princ (first remaining) stream)
             (when (rest remaining) (write-char #\Tab stream)))))

(defun write-summary (pathname rows)
  (ensure-directories-exist pathname)
  (with-open-file (stream pathname :direction :output :if-exists :supersede
                         :if-does-not-exist :create :external-format :utf-8)
    (dolist (line *summary-comment*) (write-line line stream))
    (write-line (tab-separated *summary-columns*) stream)
    (dolist (row rows) (write-line (tab-separated row) stream))))

(defun write-html-report (directory source-directory)
  (ensure-directories-exist directory)
  (let ((prefix (namestring source-directory)))
    (sb-cover:report directory :if-matches
                     (lambda (source) (uiop:string-prefix-p prefix source)))))

(defun ensure-output-directories (data-file report-directory summary-file cache-directory)
  (dolist (pathname (list (uiop:pathname-parent-directory-pathname data-file)
                          (uiop:ensure-directory-pathname report-directory)
                          (uiop:pathname-parent-directory-pathname summary-file)
                          (uiop:ensure-directory-pathname cache-directory)))
    (ensure-directories-exist pathname)))

(let* ((root (checkout-root))
       (source-directory (resolve-source-directory root))
       (data-file (environment-path "COVERAGE_OUTPUT" "cl-yaml-kit.coverage"))
       (report-directory (environment-path "COVERAGE_REPORT_DIRECTORY" "report/"))
       (summary-file (environment-path "COVERAGE_SUMMARY" "per-file.tsv"))
       (cache-directory (environment-path "COVERAGE_ASDF_CACHE" *default-cache-directory*))
       (started-at (get-internal-real-time)))
  (uiop:chdir root)
  (unless (uiop:getenv "YAML_TEST_SUITE")
    (error "YAML_TEST_SUITE must name the yaml-test-suite fixture directory."))
  (ensure-output-directories data-file report-directory summary-file cache-directory)
  (let ((asdf:*user-cache* (uiop:ensure-directory-pathname cache-directory)))
    (asdf:clear-output-translations)
    (asdf:initialize-output-translations)
    (proclaim '(optimize (sb-cover:store-coverage-data 3)))
    (asdf:load-asd (merge-pathnames "cl-yaml-kit.asd" root))
    (asdf:operate 'asdf:compile-op "cl-yaml-kit" :force t)
    (asdf:operate 'asdf:compile-op "cl-yaml-kit/test" :force t)
    (uiop:symbol-call :cl-weave :reset-coverage)
    (asdf:load-system "cl-yaml-kit/test")
    (let ((passed (handler-case (uiop:symbol-call :cl-yaml-kit/test :run-tests)
                    (serious-condition (condition)
                      (format *error-output* "~&cl-yaml-kit test run failed: ~A~%" condition)
                      nil)))
          (files (source-lisp-files source-directory)))
      (unless files (error "No *.lisp files under ~A." (namestring source-directory)))
      (let ((statistics (uiop:call-function
                         (uiop:find-symbol* :coverage-statistics :cl-weave)
                         :include-pathnames (list source-directory))))
        (when (zerop (getf statistics :expression-covered))
          (error "No covered expressions under ~A; the loaded code was not instrumented."
                 (namestring source-directory)))
        (uiop:symbol-call :cl-weave :save-coverage data-file)
        (write-html-report report-directory source-directory)
        (let ((table (coverage-source-table)))
          (require-coverage-entries table files)
          (write-summary summary-file (mapcar #'source-coverage-row files)))
        (format t "~&Coverage: ~D/~D expressions, ~D/~D branches.~%"
                (getf statistics :expression-covered) (getf statistics :expression-total)
                (getf statistics :branch-covered) (getf statistics :branch-total))
        (format t "Wrote per-file coverage to ~A in ~,1F seconds.~%"
                (namestring summary-file)
                (/ (- (get-internal-real-time) started-at)
                   internal-time-units-per-second)))
      (uiop:quit (if passed 0 1)))))
