;;;; src/char-classes.lisp
(in-package #:yaml-kit)

(define-yaml-production indicator "-?:,[]{}#&*!|>'\"%@`")
(define-yaml-production flow-indicator "[],{}")
(define-yaml-production line-break '(#\Return #\Newline))
(define-yaml-production whitespace '(#\Space #\Tab))

(declaim (inline sc-blank-p sc-break-p sc-blankz-p sc-breakz-p
                 sc-alpha-p sc-digit-p sc-hex-p sc-space-p sc-tab-p
                 sc-z-p sc-bom-p sc-printable-p))

(defun sc-blank-p (s &optional (k 0))
  (yaml-whitespace-p (sc-char s k)))
(defun sc-break-p (s &optional (k 0))
  (yaml-line-break-p (sc-char s k)))
(defun sc-blankz-p (s &optional (k 0))
  (or (sc-blank-p s k) (sc-break-p s k) (sc-z-p s k)))
(defun sc-breakz-p (s &optional (k 0))
  (or (sc-break-p s k) (sc-z-p s k)))
(defun sc-alpha-p (s &optional (k 0))
  (let ((character (sc-char s k)))
    (and (characterp character)
         (or (alphanumericp character)
             (char= character #\_) (char= character #\-)))))
(defun sc-digit-p (s &optional (k 0))
  (not (null (digit-char-p (sc-char s k) 10))))
(defun sc-hex-p (s &optional (k 0))
  (not (null (digit-char-p (sc-char s k) 16))))
(defun sc-space-p (s &optional (k 0))
  (char= (sc-char s k) #\Space))
(defun sc-tab-p (s &optional (k 0))
  (char= (sc-char s k) #\Tab))
(defun sc-z-p (s &optional (k 0))
  (char= (sc-char s k) #\Nul))
(defun sc-bom-p (s &optional (k 0))
  (char= (sc-char s k) (code-char #xfeff)))
(defun sc-printable-p (s &optional (k 0))
  (let ((code (char-code (sc-char s k))))
    (or (= code #x9) (= code #xa) (= code #xd)
        (<= #x20 code #x7e) (<= #xa0 code #x10ffff))))
