;;;; src/char-classes.lisp
(in-package #:yaml-kit)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defmacro %define-character-production (name characters)
    (let* ((suffix (string-upcase (string name)))
           (table-name (intern (format nil "+YAML-~A-BITS+" suffix)))
           (predicate-name (intern (format nil "YAML-~A-P" suffix)))
           (characters (if (and (consp characters)
                                (eq (first characters) 'quote))
                           (second characters)
                           characters))
           (bits (make-array 128 :element-type '(unsigned-byte 8)
                             :initial-element 0)))
      (loop for character across (if (stringp characters)
                                     characters
                                     (coerce characters 'string))
            do (setf (aref bits (char-code character)) 1))
      `(progn
         (defparameter ,table-name
           (make-array 128 :element-type '(unsigned-byte 8)
                       :initial-contents ',(coerce bits 'list)))
         (declaim (type (simple-array (unsigned-byte 8) (128)) ,table-name)
                  (inline ,predicate-name))
         (defun ,predicate-name (character)
           (and (characterp character) (< (char-code character) 128)
                (= 1 (aref ,table-name (char-code character))))))))

  (%define-character-production indicator "-?:,[]{}#&*!|>'\"%@`")
  (%define-character-production flow-indicator "[],{}")
  (%define-character-production line-break '(#\Return #\Newline))
  (%define-character-production whitespace '(#\Space #\Tab)))

(declaim (inline sc-blank-p sc-break-p sc-blankz-p sc-breakz-p
                 sc-alpha-p sc-digit-p sc-hex-p sc-space-p sc-tab-p
                 sc-z-p sc-bom-p sc-printable-p))

(defun sc-blank-p (s &optional (k 0))
  (yaml-whitespace-p (sc-char s k)))
(defun sc-break-p (s &optional (k 0))
  (yaml-line-break-p (sc-char s k)))
(defun sc-blankz-p (s &optional (k 0))
  (or (sc-blank-p s k) (sc-break-p s k) (sc-z-p s k)))
(defun sc-breakz-p (s &optional (k 0))
  (or (sc-break-p s k) (sc-z-p s k)))
(defun sc-alpha-p (s &optional (k 0))
  (let ((code (char-code (sc-char s k))))
    (or (<= (char-code #\0) code (char-code #\9))
        (<= (char-code #\A) code (char-code #\Z))
        (<= (char-code #\a) code (char-code #\z))
        (= code (char-code #\_))
        (= code (char-code #\-)))))
(defun sc-digit-p (s &optional (k 0))
  (let ((character (sc-char s k)))
    (char<= #\0 character #\9)))
(defun sc-hex-p (s &optional (k 0))
  (let ((character (sc-char s k)))
    (or (char<= #\0 character #\9)
        (char<= #\A character #\F)
        (char<= #\a character #\f))))
(defun sc-space-p (s &optional (k 0))
  (char= (sc-char s k) #\Space))
(defun sc-tab-p (s &optional (k 0))
  (char= (sc-char s k) #\Tab))
(defun sc-z-p (s &optional (k 0))
  (char= (sc-char s k) #\Nul))
(defun sc-bom-p (s &optional (k 0))
  (char= (sc-char s k) (code-char #xfeff)))
(defun sc-printable-p (s &optional (k 0))
  (let ((code (char-code (sc-char s k))))
    (or (= code #x9) (= code #xa) (= code #xd)
        (<= #x20 code #x7e) (<= #xa0 code #x10ffff))))
