(in-package #:yaml-kit)

(declaim (inline %limit!))

(defun %limit! (value limit)
  (when (and limit (> value limit))
    (error 'yaml-resource-limit-error)))

(defun compose-all-events (events &key (max-input-length 104857600)
                                     (max-depth 1000)
                                     (max-scalar-length 16777216)
                                     (max-nodes 1000000)
                                     (max-alias-expansions 100000))
  "Compose EVENTS without retaining an intermediate event list."
  (declare (optimize (speed 3) (safety 1)))
  (let ((documents nil) (current nil) (stack nil) (anchors nil)
        (nodes 0) (depth 0) (aliases 0))
    (labels
        ((append-node (node)
           (if stack
               (push node (cdr (car stack)))
               (if current
                   (error 'yaml-compose-error)
                   (setf current node))))
         (start-document ()
           (setf current nil stack nil depth 0
                 anchors (make-hash-table :test #'equal)))
         (finish-node ()
           (unless stack (error 'yaml-compose-error))
           (let* ((frame (pop stack))
                  (node (car frame))
                  (children (nreverse (cdr frame))))
             (if (sequence-node-p node)
                 (setf (sequence-node-items node) children)
                 (progn
                   (unless (evenp (length children))
                     (error 'yaml-compose-error))
                   (setf (mapping-node-pairs node)
                         (loop for (key value) on children by #'cddr
                               collect (cons key value)))))
             (decf depth)
             (if stack
                 (push node (cdr (car stack)))
                 (if current
                     (error 'yaml-compose-error)
                     (setf current node)))))
         (start-collection (event sequence-p)
           (let ((node (if sequence-p
                           (make-sequence-node
                            :tag (sequence-start-event-tag event)
                            :anchor (sequence-start-event-anchor event)
                            :style (sequence-start-event-style event)
                            :start-mark (event-start-mark event)
                            :end-mark (event-end-mark event))
                           (make-mapping-node
                            :tag (mapping-start-event-tag event)
                            :anchor (mapping-start-event-anchor event)
                            :style (mapping-start-event-style event)
                            :start-mark (event-start-mark event)
                            :end-mark (event-end-mark event)))))
             (incf nodes)
             (%limit! nodes max-nodes)
             (when (node-anchor node)
               (setf (gethash (node-anchor node) anchors) node))
             (incf depth)
             (%limit! depth max-depth)
             (push (cons node nil) stack)))
         (handle (event)
           (cond
             ((or (stream-start-event-p event) (stream-end-event-p event)) nil)
             ((document-start-event-p event) (start-document))
             ((document-end-event-p event)
              (when stack (error 'yaml-compose-error))
              (when current (push current documents))
              (setf current nil))
             ((alias-event-p event)
              (incf aliases)
              (%limit! aliases max-alias-expansions)
              (multiple-value-bind (node presentp)
                  (gethash (alias-event-anchor event) anchors)
                (unless presentp (error 'yaml-compose-error))
                (incf nodes)
                (%limit! nodes max-nodes)
                (append-node node)))
             ((scalar-event-p event)
              (let ((value (scalar-event-value event)))
                (%limit! (length value) max-scalar-length)
                (let ((node (make-scalar-node
                           :tag (scalar-event-tag event)
                           :anchor (scalar-event-anchor event)
                           :style (scalar-event-style event)
                           :start-mark (event-start-mark event)
                           :end-mark (event-end-mark event)
                           :value value)))
                  (incf nodes)
                  (%limit! nodes max-nodes)
                  (when (node-anchor node)
                    (setf (gethash (node-anchor node) anchors) node))
                  (append-node node))))
             ((sequence-start-event-p event) (start-collection event t))
             ((mapping-start-event-p event) (start-collection event nil))
             ((or (sequence-end-event-p event) (mapping-end-event-p event))
              (finish-node))
             (t (error 'yaml-compose-error)))))
      (if (listp events)
          (dolist (event events) (handle event))
          (map-events #'handle events
                      :max-input-length max-input-length
                      :max-depth max-depth
                      :max-scalar-length max-scalar-length)))
      (when stack (error 'yaml-compose-error))
      (when current (push current documents))
      (nreverse documents)))

(defun compose-events (events &rest options)
  (car (apply #'compose-all-events (cons events options))))
