;;;; src/composer.lisp
(in-package #:yaml-kit)

(declaim (inline %limit!))

(defun %limit! (value limit)
  (when (and limit (> value limit))
    (error 'yaml-resource-limit-error)))

(defun %event-list (events)
  (if (listp events)
      events
      (error 'yaml-compose-error)))

(defun compose-all-events (events &key (max-nodes 1000000) (max-depth 1000)
                                     (max-alias-expansions 100000))
  (declare (optimize (speed 3) (safety 1)))
  (let ((documents nil) (current nil) (stack nil)
        (anchors (make-hash-table :test #'equal))
        (nodes 0) (depth 0) (aliases 0))
    (labels ((add-node (node)
               (incf nodes) (%limit! nodes max-nodes)
               (if stack
                   (push node (cdr (car stack)))
                   (setf current node))))
      (dolist (event (%event-list events))
        (cond
          ((or (stream-start-event-p event) (stream-end-event-p event)) nil)
          ((document-start-event-p event)
           (setf current nil stack nil depth 0
                 anchors (make-hash-table :test #'equal)))
          ((document-end-event-p event)
           (when current (push current documents))
           (setf current nil))
          ((alias-event-p event)
           (incf aliases) (%limit! aliases max-alias-expansions)
           (let ((node (gethash (alias-event-anchor event) anchors)))
             (unless node (error 'yaml-compose-error))
             (add-node node)))
          ((scalar-event-p event)
           (let ((node (make-scalar-node :tag (scalar-event-tag event)
                                          :anchor (scalar-event-anchor event)
                                          :style (scalar-event-style event)
                                          :start-mark (event-start-mark event)
                                          :end-mark (event-end-mark event)
                                          :value (scalar-event-value event))))
             (incf nodes) (%limit! nodes max-nodes)
             (when (scalar-event-anchor event)
               (setf (gethash (scalar-event-anchor event) anchors) node))
             (if stack (push node (cdr (car stack))) (setf current node))))
          ((or (sequence-start-event-p event) (mapping-start-event-p event))
           (let ((node (if (sequence-start-event-p event)
                           (make-sequence-node :tag (sequence-start-event-tag event)
                                               :anchor (sequence-start-event-anchor event)
                                               :style (sequence-start-event-style event)
                                               :start-mark (event-start-mark event)
                                               :end-mark (event-end-mark event))
                           (make-mapping-node :tag (mapping-start-event-tag event)
                                              :anchor (mapping-start-event-anchor event)
                                              :style (mapping-start-event-style event)
                                              :start-mark (event-start-mark event)
                                              :end-mark (event-end-mark event)))))
             (incf nodes) (%limit! nodes max-nodes)
             (when (node-anchor node)
               (setf (gethash (node-anchor node) anchors) node))
             (incf depth) (%limit! depth max-depth)
             (push (cons node nil) stack)))
          ((or (sequence-end-event-p event) (mapping-end-event-p event))
           (unless stack (error 'yaml-compose-error))
           (let* ((frame (pop stack)) (node (car frame))
                  (children (nreverse (cdr frame))))
             (if (sequence-node-p node)
                 (setf (sequence-node-items node) children)
                 (setf (mapping-node-pairs node)
                       (loop for (key value) on children by #'cddr
                             collect (cons key value))))
             (decf depth)
             (if stack (push node (cdr (car stack))) (setf current node))))
          (t (error 'yaml-compose-error))))
      (when stack (error 'yaml-compose-error))
      (nreverse documents))))

(defun compose-events (events &rest options)
  (car (apply #'compose-all-events events options)))
