;;;; src/conditions.lisp
(in-package #:yaml-kit)

(define-condition yaml-kit-error (error) ())
(define-condition yaml-parse-error (yaml-kit-error)
  ((line :initarg :line :initform 1 :reader yaml-parse-error-line)
   (column :initarg :column :initform 1 :reader yaml-parse-error-column)
   (offset :initarg :offset :initform 0 :reader yaml-parse-error-offset)
   (context :initarg :context :initform "YAML" :reader yaml-parse-error-context))
  (:report (lambda (condition stream)
            (format stream "YAML parse error at line ~D, column ~D, offset ~D: ~A"
                    (yaml-parse-error-line condition)
                    (yaml-parse-error-column condition)
                    (yaml-parse-error-offset condition)
                    (yaml-parse-error-context condition)))))
(define-condition yaml-compose-error (yaml-kit-error) ()
  (:report (lambda (condition stream) (declare (ignore condition))
            (write-string "YAML compose error" stream))))
(define-condition yaml-emit-error (yaml-kit-error) ()
  (:report (lambda (condition stream) (declare (ignore condition))
            (write-string "YAML emit error" stream))))
(define-condition yaml-resource-limit-error (yaml-kit-error) ()
  (:report (lambda (condition stream) (declare (ignore condition))
            (write-string "YAML resource limit exceeded" stream))))
