;;;; src/conditions.lisp
(in-package #:yaml-kit)

(defun %write-yaml-condition-context (stream prefix context mark)
  (if mark
      (format stream "~A at line ~D, column ~D, offset ~D: ~A"
              prefix (mark-line mark) (mark-column mark) (mark-offset mark)
              context)
      (format stream "~A: ~A" prefix context)))

(define-condition yaml-kit-error (error)
  ((message :initarg :message :initform nil :reader yaml-kit-error-message))
  (:report (lambda (condition stream)
             (if (yaml-kit-error-message condition)
                 (write-string (yaml-kit-error-message condition) stream)
                 (write-string "YAML error" stream)))))
(define-condition yaml-parse-error (yaml-kit-error)
  ((line :initarg :line :initform 1 :reader yaml-parse-error-line)
   (column :initarg :column :initform 1 :reader yaml-parse-error-column)
   (offset :initarg :offset :initform 0 :reader yaml-parse-error-offset)
   (context :initarg :context :initform "YAML" :reader yaml-parse-error-context))
  (:report (lambda (condition stream)
            (format stream "YAML parse error at line ~D, column ~D, offset ~D: ~A~@[ (~A)~]"
                    (yaml-parse-error-line condition)
                    (yaml-parse-error-column condition)
                    (yaml-parse-error-offset condition)
                    (yaml-parse-error-context condition)
                    (yaml-kit-error-message condition)))))
(define-condition yaml-compose-error (yaml-kit-error)
  ((mark :initarg :mark :initform nil :reader yaml-compose-error-mark)
   (context :initarg :context :initform "YAML" :reader yaml-compose-error-context))
  (:report (lambda (condition stream)
             (%write-yaml-condition-context
              stream "YAML compose error" (yaml-compose-error-context condition)
              (yaml-compose-error-mark condition))
             (when (yaml-kit-error-message condition)
               (format stream "; ~A" (yaml-kit-error-message condition))))))
(define-condition yaml-emit-error (yaml-kit-error)
  ((mark :initarg :mark :initform nil :reader yaml-emit-error-mark)
   (context :initarg :context :initform "YAML" :reader yaml-emit-error-context))
  (:report (lambda (condition stream)
             (%write-yaml-condition-context
              stream "YAML emit error" (yaml-emit-error-context condition)
              (yaml-emit-error-mark condition))
             (when (yaml-kit-error-message condition)
               (format stream "; ~A" (yaml-kit-error-message condition))))))
(define-condition yaml-resource-limit-error (yaml-kit-error)
  ((limit-name :initarg :limit-name :initform "resource" :reader yaml-resource-limit-error-limit-name)
   (limit :initarg :limit :initform nil :reader yaml-resource-limit-error-limit)
   (actual :initarg :actual :initform nil :reader yaml-resource-limit-error-actual)
   (mark :initarg :mark :initform nil :reader yaml-resource-limit-error-mark)
   (context :initarg :context :initform "YAML" :reader yaml-resource-limit-error-context))
  (:report (lambda (condition stream)
             (%write-yaml-condition-context
              stream "YAML resource limit exceeded"
              (yaml-resource-limit-error-context condition)
              (yaml-resource-limit-error-mark condition))
             (format stream " (~A limit ~S, actual ~S)"
                     (yaml-resource-limit-error-limit-name condition)
                     (yaml-resource-limit-error-limit condition)
                     (yaml-resource-limit-error-actual condition))
             (when (yaml-kit-error-message condition)
               (format stream "; ~A" (yaml-kit-error-message condition))))))
