(in-package #:yaml-kit)

(declaim (inline %collection-tag-compatible-p %construct-sequence
                %construct-mapping))

(defun %scalar-kind (node schema)
  (let ((tag (node-tag node)))
    (cond
      ((or (null tag) (and tag (string= tag "?")))
       (if (eq (node-style node) :plain)
           (if (member schema '(:core :json))
                (let ((resolved-tag (resolve-tag node :schema schema)))
                 (or (%tag-kind resolved-tag) :str))
               :str)
           :str))
      ((string= tag "!") :str)
      ((%tag-kind tag) (%tag-kind tag))
      (t :str))))

(defun %parse-number (text kind)
  (declare (optimize (speed 3) (safety 1)))
  (handler-case
      (case kind
        (:int
         (let* ((sign-position (if (and (> (length text) 0)
                                        (member (char text 0) '(#\+ #\-)))
                                   1 0))
                (sign (if (and (plusp sign-position)
                               (char= (char text 0) #\-)) -1 1)))
           (cond
             ((and (<= (+ sign-position 2) (length text))
                   (char-equal (char text sign-position) #\0)
                   (char-equal (char text (1+ sign-position)) #\o))
              (* sign (parse-integer text :radix 8 :start (+ sign-position 2))))
             ((and (<= (+ sign-position 2) (length text))
                   (char-equal (char text sign-position) #\0)
                   (char-equal (char text (1+ sign-position)) #\x))
              (* sign (parse-integer text :radix 16 :start (+ sign-position 2))))
             (t (parse-integer text)))))
        (:float
         (cond
           ((member text '(".nan" ".NaN" ".NAN") :test #'string=)
            (sb-kernel:make-double-float #x7ff80000 1))
           ((member text '(".inf" ".Inf" ".INF" "+.inf" "+.Inf" "+.INF")
                    :test #'string=)
            sb-kernel::double-float-positive-infinity)
           ((member text '("-.inf" "-.Inf" "-.INF") :test #'string=)
            sb-kernel::double-float-negative-infinity)
           (t
            (let ((*read-default-float-format* 'double-float))
              (multiple-value-bind (number end)
                  (read-from-string text)
                (unless (= end (length text))
                  (error 'yaml-compose-error))
                (coerce number 'double-float))))))
    (error () (error 'yaml-compose-error)))))

(defun %construct-scalar (node schema)
  (let* ((text (scalar-node-value node))
         (kind (%scalar-kind node schema))
         (tag (node-tag node)))
    (case kind
      (:invalid-collection (error 'yaml-compose-error))
      (:null (unless (member text '("" "~" "null" "Null" "NULL")
                              :test #'string=)
                (error 'yaml-compose-error))
             +yaml-null+)
      (:bool (cond ((member text '("true" "True" "TRUE") :test #'string=) t)
                   ((member text '("false" "False" "FALSE") :test #'string=)
                    +yaml-false+)
                   (t (error 'yaml-compose-error))))
      (:int (%parse-number text kind))
      (:float
       (let ((number (%parse-number text kind)))
         (if (and (or (null tag) (string= tag "?")))
             (handler-case
                 (multiple-value-bind (integer remainder) (truncate number)
                   (if (zerop remainder) integer number))
               (arithmetic-error () number))
             number)))
      (t text))))

(defun %collection-tag-compatible-p (node expected)
  (let ((tag (node-tag node)))
    (or (null tag)
        (member tag '("!" "?") :test #'string=)
        (string= (%canonical-tag tag) expected)
        (and (not (%tag-info tag)) (not (%collection-tag-p tag))))))

(defun %construct-sequence (node sequence-type memo walk)
  (multiple-value-bind (cached presentp) (gethash node memo)
    (if presentp
        cached
        (if (eq sequence-type :list)
            (let ((items (sequence-node-items node)))
              (if (null items)
                  nil
                  (let ((result (cons nil nil)))
                    (setf (gethash node memo) result)
                    (loop for rest on items
                          for cell = result then (cdr cell)
                          do (setf (car cell) (funcall walk (car rest)))
                          when (cdr rest)
                            do (setf (cdr cell) (cons nil nil))
                          finally (setf (cdr cell) nil))
                    result)))
            (let* ((items (sequence-node-items node))
                   (result (make-array (length items))))
              (setf (gethash node memo) result)
              (loop for item in items for i from 0
                    do (setf (aref result i) (funcall walk item)))
              result)))))

(defun %alist-mapping (pairs duplicate-key-policy memo node walk)
  (let ((result (make-list (length pairs))) (tail nil) (last-cell nil)
        (seen (make-hash-table :test #'equal)))
    (setf (gethash node memo) result tail result)
    (dolist (pair pairs)
      (let ((key (funcall walk (car pair))) (value (funcall walk (cdr pair))))
        (multiple-value-bind (old presentp) (gethash key seen)
          (when (and presentp (eq duplicate-key-policy :error))
            (error 'yaml-compose-error))
          (unless (and presentp (eq duplicate-key-policy :first))
            (if (and presentp (eq duplicate-key-policy :last))
                (setf (cdr old) value)
                (setf (car tail) (cons key value) last-cell tail tail (cdr tail))))
          (setf (gethash key seen) (or old (car last-cell))))))
    (when last-cell (setf (cdr last-cell) nil))
    result))

(defun %construct-mapping (node mapping-type duplicate-key-policy memo walk)
  (or (gethash node memo)
      (let ((pairs (mapping-node-pairs node)))
        (case mapping-type
          (:alist (%alist-mapping pairs duplicate-key-policy memo node walk))
          (:yaml-mapping
           (let* ((result (make-yaml-mapping (make-list (length pairs))))
                  (entries (yaml-mapping-entries result)))
             (setf (gethash node memo) result)
             (loop for pair in pairs for cell on entries
                   do (setf (car cell)
                            (cons (funcall walk (car pair)) (funcall walk (cdr pair)))))
             result))
          (:hash-table
           (let ((table (make-hash-table :test #'equal :size (max 1 (length pairs)))))
             (setf (gethash node memo) table)
             (dolist (pair pairs table)
               (let ((key (funcall walk (car pair))) (value (funcall walk (cdr pair))))
                 (when (or (consp key) (and (vectorp key) (not (stringp key)))
                           (yaml-mapping-p key))
                   (error 'yaml-compose-error))
                 (multiple-value-bind (old presentp) (gethash key table)
                   (declare (ignore old))
                   (when (and presentp (eq duplicate-key-policy :error))
                     (error 'yaml-compose-error))
                   (unless (and presentp (eq duplicate-key-policy :first))
                     (setf (gethash key table) value)))))))))))

(defun construct (node &key (schema :core) (mapping-type :hash-table)
                              (sequence-type :vector)
                              (duplicate-key-policy :error)
                              &allow-other-keys)
  "Construct NODE.  Non-scalar hash-table keys are rejected explicitly."
  (declare (optimize (speed 3) (safety 1)))
  (unless (member mapping-type '(:hash-table :alist :yaml-mapping))
    (error 'yaml-compose-error))
  (unless (member sequence-type '(:vector :list))
    (error 'yaml-compose-error))
  (unless (member duplicate-key-policy '(:error :first :last))
    (error 'yaml-compose-error))
  (let ((memo (make-hash-table :test #'eq)))
    (labels ((walk (object)
               (cond
                 ((scalar-node-p object) (%construct-scalar object schema))
                 ((sequence-node-p object)
                  (unless (%collection-tag-compatible-p object
                                                         "tag:yaml.org,2002:seq")
                    (error 'yaml-compose-error))
                  (%construct-sequence object sequence-type memo #'walk))
                 ((mapping-node-p object)
                  (unless (%collection-tag-compatible-p object
                                                         "tag:yaml.org,2002:map")
                    (error 'yaml-compose-error))
                  (%construct-mapping object mapping-type duplicate-key-policy
                                       memo #'walk))
                 (t (error 'yaml-compose-error)))))
      (walk node))))
