;;;; src/constructor.lisp
(in-package #:yaml-kit)

(defun %tag-name (tag)
  (subseq tag (1+ (or (position #\: tag :from-end t) -1))))

(defun %number (text kind)
  (declare (optimize (speed 3) (safety 1)))
  (let ((clean (delete #\_ text)))
    (case kind
      (:int
       (cond ((search "0o" clean :test #'char-equal)
              (* (if (char= (char clean 0) #\-) -1 1)
                 (parse-integer clean :radix 8 :start (+ 2 (if (member (char clean 0)
                                                                         '(#\+ #\-)) 1 0)))))
             ((search "0x" clean :test #'char-equal)
              (* (if (char= (char clean 0) #\-) -1 1)
                 (parse-integer clean :radix 16 :start (+ 2 (if (member (char clean 0)
                                                                          '(#\+ #\-)) 1 0)))))
             (t (parse-integer clean))))
      (:float
       (cond ((string-equal clean ".nan")
              (sb-kernel:make-double-float #x7ff80000 1))
             ((or (string-equal clean ".inf")
                  (string-equal clean "+.inf"))
              sb-kernel::double-float-positive-infinity)
             ((string-equal clean "-.inf")
              sb-kernel::double-float-negative-infinity)
             (t (coerce (read-from-string clean) 'double-float)))))))

(defun construct (node &key (schema :core) (mapping-type :hash-table)
                              (sequence-type :vector)
                              (duplicate-key-policy :error)
                              &allow-other-keys)
  "Return the Common Lisp value represented by NODE."
  (declare (optimize (speed 3) (safety 1)))
  (let ((memo (make-hash-table :test #'eq)))
    (labels ((walk (node)
             (cond
               ((scalar-node-p node)
                (let* ((tag (resolve-tag node :schema schema))
                       (kind (intern (string-upcase (%tag-name tag)) :keyword))
                       (text (scalar-node-value node)))
                  (case kind
                    (:null +yaml-null+)
                    (:bool (if (member text '("true" "True" "TRUE") :test #'string=)
                               t +yaml-false+))
                    ((:int :float) (%number text kind))
                    (t text))))
               ((sequence-node-p node)
                (or (gethash node memo)
                    (if (eq sequence-type :list)
                        (let ((items (mapcar #'walk (sequence-node-items node))))
                          (setf (gethash node memo) items) items)
                        (let ((result (make-array (length (sequence-node-items node)))))
                          (setf (gethash node memo) result)
                          (loop for item in (sequence-node-items node)
                                for index from 0
                                do (setf (aref result index) (walk item)))
                          result))))
               ((mapping-node-p node)
                (or (gethash node memo)
                    (let ((pairs (mapping-node-pairs node)))
                  (if (eq mapping-type :alist)
                      (let ((result nil))
                        (dolist (pair pairs (nreverse result))
                          (let ((key (walk (car pair))) (value (walk (cdr pair))))
                            (when (and (eq duplicate-key-policy :error)
                                       (find key result :key #'car :test #'equalp))
                              (error 'yaml-compose-error))
                            (push (cons key value) result))))
                      (if (eq mapping-type :yaml-mapping)
                          (make-yaml-mapping
                           (mapcar (lambda (pair)
                                     (cons (walk (car pair)) (walk (cdr pair))))
                                   pairs))
                          (let ((table (make-hash-table :test #'equal
                                                        :size (max 1 (length pairs)))))
                            (setf (gethash node memo) table)
                        (dolist (pair pairs table)
                          (let ((key (walk (car pair))) (value (walk (cdr pair))))
                            (when (and (not (or (stringp key) (numberp key)
                                                 (symbolp key) (characterp key)))
                                       (not (eq mapping-type :alist)))
                              (error 'yaml-compose-error))
                            (when (and (eq duplicate-key-policy :error)
                                       (gethash key table))
                              (error 'yaml-compose-error))
                            (setf (gethash key table) value))))))))))))
      (walk node))))
