(in-package #:yaml-kit)

(defun emit-event-stream (events stream &key (indent 2)
                                      (explicit-document-start nil)
                                      (suppress-empty-document-marker nil))
  (let ((context (make-emitter-context stream indent))
        (stack nil)
        (first-document t)
        (last-key-style nil))
    (labels ((flow-p () (and stack (member (caar stack) '(:flow :flow-map))))
             (map-p () (and stack (member (caar stack) '(:map :map-after-explicit-key :flow-map))))
             (separator ()
               (when (and stack (flow-p) (plusp (cdar stack)))
                 (%emit-text context ", ")))
             (start-value (&optional event)
               (when stack
                 (let ((frame (car stack)))
                   (cond
                     ((eq (car frame) :explicit-key-seq)
                      (if (zerop (cdr frame))
                          (%emit-text context "- ")
                          (progn
                            (%emit-newline context)
                            (%emit-text context
                                        (make-string (* (1- (length stack)) indent)
                                                     :initial-element #\Space))
                            (%emit-text context "- "))))
                     ((eq (car frame) :inline-seq)
                      (if (zerop (cdr frame))
                          (%emit-text context "- ")
                          (progn
                            (%emit-newline context)
                            (%emit-text context
                                        (make-string (* (1- (length stack)) indent)
                                                     :initial-element #\Space))
                            (%emit-text context "- "))))
                     ((eq (car frame) :indentless-seq)
                      (if (zerop (cdr frame))
                          (%emit-text context "- ")
                          (progn
                            (%emit-newline context)
                            (%emit-text context "- "))))
                     ((map-p)
                       (if (oddp (cdr frame))
                          (%emit-text context
                                      (cond
                                        ((and (sequence-start-event-p event)
                                              (eq last-key-style :double-quoted)
                                              (eq (sequence-start-event-style event) :block))
                                         ":")
                                        ((and (scalar-event-p event)
                                              (zerop (length (scalar-event-value event)))
                                              (eq (funcall #'scalar-event-style event) :plain))
                                         ":")
                                        (t ": ")))
                          (if (and (eq (car frame) :map)
                                   (zerop (cdr frame))
                                   (not (emitter-context-line-start context)))
                              nil
                              (if (and (sequence-start-event-p event)
                                       (eq last-key-style :double-quoted)
                                       (eq (sequence-start-event-style event) :block))
                                  (%emit-text context ":")
                                  (if (flow-p)
                              (separator)
                              (progn
                                (unless (emitter-context-line-start context)
                                  (%emit-newline context))
                                (%emit-text context
                                            (make-string (* (1- (length stack)) indent)
                                                         :initial-element #\Space))))))))
                     ((emitter-context-line-start context)
                      (%emit-text context
                                  (make-string (* (1- (length stack)) indent)
                                               :initial-element #\Space))
                      (%emit-text context "- "))
                     ((flow-p)
                      (separator))
                     (t
                      (%emit-newline context)
                      (%emit-text context
                                  (make-string (* (1- (length stack)) indent)
                                               :initial-element #\Space))
                      (%emit-text context "- ")))))))
      (loop for remaining on events
            for event = (car remaining)
            do (cond
          ((stream-start-event-p event))
          ((stream-end-event-p event)
           (unless (emitter-context-line-start context) (%emit-newline context)))
          ((document-start-event-p event)
           (%emit-document-directives event context)
           (when (or explicit-document-start
                     (document-start-event-explicit-p event)
                     (document-start-event-version event)
                     (document-start-event-tag-directives event)
                     (and (not suppress-empty-document-marker)
                          (cdr remaining)
                          (document-end-event-p (car (cdr remaining))))
                     (and (not suppress-empty-document-marker)
                          (cddr remaining)
                          (or (and (sequence-start-event-p (cadr remaining))
                                   (sequence-end-event-p (caddr remaining)))
                              (and (mapping-start-event-p (cadr remaining))
                                   (mapping-end-event-p (caddr remaining)))))
                     (and (cdr remaining)
                          (document-end-event-p (cadr remaining))))
             (when (and (not first-document)
                        (not (emitter-context-line-start context)))
               (%emit-newline context))
             (%emit-text context "---")
             (if (and (cdr remaining)
                     (or (scalar-event-p (cadr remaining))
                          (alias-event-p (cadr remaining))
                          (and (sequence-start-event-p (cadr remaining))
                               (eq (sequence-start-event-style (cadr remaining)) :flow))
                          (and (cddr remaining)
                               (or (and (sequence-start-event-p (cadr remaining))
                                        (sequence-end-event-p (caddr remaining)))
                                   (and (mapping-start-event-p (cadr remaining))
                                        (mapping-end-event-p (caddr remaining)))))))
                 (if (and (scalar-event-p (cadr remaining))
                          (zerop (length (scalar-event-value (cadr remaining)))))
                     (%emit-newline context)
                     (%emit-text context " "))
                 (%emit-newline context)))
           (setf first-document nil))
          ((document-end-event-p event)
           (when (document-end-event-explicit-p event)
             (unless (emitter-context-line-start context) (%emit-newline context))
             (%emit-text context "...")
             (%emit-newline context))
          (unless (emitter-context-line-start context) (%emit-newline context)))
          ((scalar-event-p event)
           (start-value event)
           (%emit-prefix event context)
           (let* ((value (scalar-event-value event))
                  (empty (zerop (length value)))
                  (key-p (and stack (map-p) (evenp (cdr (car stack)))))
                  (style (if (and (or key-p
                                      (and stack (map-p) (oddp (cdr (car stack)))))
                                  (eq (scalar-event-style event) :plain)
                                  (plusp (length value))
                                  (or (char= (char value 0) #\?)
                                      (and (char= (char value 0) #\:)
                                           (> (length value) 1)
                                           (not (%yaml-blank-p (char value 1))))))
                             :plain
                             (%scalar-style value (scalar-event-style event)
                                            (flow-p)
                                            (scalar-event-tag event)))))
             (unless (and empty
                          (eq (scalar-event-style event) :plain)
                          (null (scalar-event-tag event)))
             (%write-scalar value
                            style
                            context
                            (* (max 1 (length stack)) indent)
                            (not (some (lambda (candidate)
                                         (and (document-end-event-p candidate)
                                              (document-end-event-explicit-p candidate)))
                                       remaining))))
             (when stack (incf (cdr (car stack))))
           (when key-p
               (setf last-key-style style))))
          ((alias-event-p event)
           (start-value)
           (%emit-text context "*")
           (%emit-text context (alias-event-anchor event))
           (when stack (incf (cdr (car stack)))))
          ((sequence-start-event-p event)
           (if (and stack (member (caar stack) '(:map :map-after-explicit-key))
                    (evenp (cdar stack))
                    (eq (sequence-start-event-style event) :block))
               (progn
                 (unless (emitter-context-line-start context)
                   (%emit-newline context))
                 (%emit-text context "? "))
               (progn
                 (when (and (eq (caar stack) :map-after-explicit-key)
                            (not (emitter-context-line-start context)))
                   (%emit-newline context))
                 (start-value event)))
           (when (and stack (eq (caar stack) :map)
                      (oddp (cdar stack))
                      (eq last-key-style :double-quoted))
             (%emit-newline context))
           (%emit-prefix event context)
           (push (cons (if (and stack
                                (member (caar stack) '(:map :map-after-explicit-key))
                                (evenp (cdar stack))
                                (eq (sequence-start-event-style event) :block))
                           :explicit-key-seq
                           (if (and stack (eq (caar stack) :map-after-explicit-key))
                               :inline-seq
                           (if (and stack (eq (caar stack) :map)
                                    (oddp (cdar stack))
                                    (eq last-key-style :double-quoted))
                               :indentless-seq
                           (if (or (eq (sequence-start-event-style event) :flow)
                               (and (cdr remaining)
                                    (sequence-end-event-p (cadr remaining))))
                           :flow
                           :seq))))
                       0)
                 stack)
           (when (and (cdr stack)
                      (eq (caar (cdr stack)) :map-after-explicit-key))
             (setf (caar (cdr stack)) :map))
           (when (flow-p) (%emit-text context "[")))
          ((mapping-start-event-p event)
           (let ((key-p (and stack (map-p) (evenp (cdar stack)))))
           (start-value)
           (when (and stack
                      (eq (caar stack) :map)
                      (oddp (cdar stack))
                      (eq (mapping-start-event-style event) :block)
                      (null (mapping-start-event-anchor event))
                      (null (mapping-start-event-tag event))
                      (not (emitter-context-line-start context)))
             (%emit-newline context))
           (%emit-prefix event context)
           (when (and stack
                      (eq (caar stack) :map)
                      (oddp (cdar stack))
                      (eq (mapping-start-event-style event) :block)
                      (or (mapping-start-event-anchor event)
                          (mapping-start-event-tag event))
                      (not (emitter-context-line-start context)))
             (%emit-newline context))
           (push (cons (if (or (and (eq (mapping-start-event-style event) :flow)
                                  (or key-p (flow-p)))
                               (and (cdr remaining)
                                    (mapping-end-event-p (cadr remaining))))
                           :flow-map
                           :map)
                       0)
                 stack)
           (when (flow-p) (%emit-text context "{"))))
          ((sequence-end-event-p event)
           (let ((frame (pop stack)))
             (when (eq (car frame) :flow) (%emit-text context "]"))
             (when stack
               (incf (cdr (car stack)))
               (when (eq (car frame) :explicit-key-seq)
                 (setf (caar stack) :map-after-explicit-key)))))
          ((mapping-end-event-p event)
           (let ((frame (pop stack)))
             (when (eq (car frame) :flow-map) (%emit-text context "}"))
             (when stack (incf (cdr (car stack)))))))
      ))
    stream))
