(in-package #:yaml-kit)

(defun %emit-prefix (event context)
  (when (or (scalar-event-p event) (sequence-start-event-p event)
            (mapping-start-event-p event))
    (let ((anchor (cond ((scalar-event-p event) (scalar-event-anchor event))
                        ((sequence-start-event-p event) (sequence-start-event-anchor event))
                        (t (mapping-start-event-anchor event)))))
      (when anchor
        (%emit-text context "&")
        (%emit-text context anchor)
        (%emit-text context " ")))
    (let ((tag (cond ((scalar-event-p event) (scalar-event-tag event))
                     ((sequence-start-event-p event) (sequence-start-event-tag event))
                     (t (mapping-start-event-tag event)))))
      (when (and tag (not (member tag +implicit-scalar-tags+ :test #'string=)))
        (%emit-text context
                    (cond ((string= tag "!") "!")
                          ((and (>= (length tag) 5)
                                (string= tag "tag:" :end1 4))
                           (concatenate 'simple-string "!<" tag ">"))
                          ((char= (char tag 0) #\!) tag)
                          (t (concatenate 'simple-string "!" tag))))
        (%emit-text context " ")))))

(defun %emit-document-directives (event context)
  (when (document-start-event-version event)
    (%emit-text context "%YAML ")
    (%emit-text context (document-start-event-version event))
    (%emit-newline context))
  (dolist (directive (document-start-event-tag-directives event))
    (%emit-text context "%TAG ")
    (%emit-text context (car directive))
    (%emit-text context " ")
    (%emit-text context (cdr directive))
    (%emit-newline context)))

