(in-package #:yaml-kit)

(defstruct (emitter-frame-state (:constructor make-emitter-frame-state
                                  (context indent explicit suppress)))
  context indent explicit suppress stack (first-document t) last-key-style)

(defun %frame-flow-p (state)
  (and (emitter-frame-state-stack state)
       (member (caar (emitter-frame-state-stack state)) '(:flow :flow-map))))
(defun %frame-map-p (state)
  (and (emitter-frame-state-stack state)
       (member (caar (emitter-frame-state-stack state))
               '(:map :map-after-explicit-key :flow-map))))
(defun %frame-indent (state)
  (make-string (* (1- (length (emitter-frame-state-stack state)))
                  (emitter-frame-state-indent state)) :initial-element #\Space))
(defun %frame-separator (state)
  (when (and (%frame-flow-p state)
             (plusp (cdar (emitter-frame-state-stack state))))
    (%emit-text (emitter-frame-state-context state) ", ")))

(defun %frame-start-value (state &optional event)
  (when (emitter-frame-state-stack state)
    (let* ((context (emitter-frame-state-context state))
           (stack (emitter-frame-state-stack state)) (frame (car stack)))
      (cond
        ((member (car frame) '(:explicit-key-seq :inline-seq))
         (if (zerop (cdr frame)) (%emit-text context "- ")
             (progn (%emit-newline context) (%emit-text context (%frame-indent state))
                    (%emit-text context "- "))))
        ((eq (car frame) :indentless-seq)
         (if (zerop (cdr frame)) (%emit-text context "- ")
             (progn (%emit-newline context) (%emit-text context "- "))))
        ((%frame-map-p state)
         (if (oddp (cdr frame))
             (%emit-text context
                         (if (or (and (scalar-event-p event)
                                      (zerop (length (scalar-event-value event)))
                                      (eq (scalar-event-style event) :plain)
                                      (null (scalar-event-tag event)))
                                 (and (sequence-start-event-p event)
                                      (eq (emitter-frame-state-last-key-style state)
                                          :double-quoted)
                                      (eq (sequence-start-event-style event) :block)))
                             ":" ": "))
             (unless (and (eq (car frame) :map) (zerop (cdr frame))
                          (not (emitter-context-line-start context)))
               (if (and (sequence-start-event-p event)
                        (eq (emitter-frame-state-last-key-style state) :double-quoted)
                        (eq (sequence-start-event-style event) :block))
                   (%emit-text context ":")
                   (if (%frame-flow-p state) (%frame-separator state)
                       (progn (unless (emitter-context-line-start context)
                                (%emit-newline context))
                              (%emit-text context (%frame-indent state))))))))
        ((emitter-context-line-start context)
         (%emit-text context (%frame-indent state)) (%emit-text context "- "))
        ((%frame-flow-p state) (%frame-separator state))
        (t (%emit-newline context) (%emit-text context (%frame-indent state))
           (%emit-text context "- "))))))

(defun %frame-kind (state event next)
  (cond ((and (emitter-frame-state-stack state)
              (member (caar (emitter-frame-state-stack state))
                      '(:map :map-after-explicit-key))
              (evenp (cdar (emitter-frame-state-stack state)))
              (eq (sequence-start-event-style event) :block)) :explicit-key-seq)
        ((and (emitter-frame-state-stack state)
              (eq (caar (emitter-frame-state-stack state)) :map-after-explicit-key))
         :inline-seq)
        ((and (emitter-frame-state-stack state)
              (eq (caar (emitter-frame-state-stack state)) :map)
              (oddp (cdar (emitter-frame-state-stack state)))
              (eq (emitter-frame-state-last-key-style state) :double-quoted))
         :indentless-seq)
        ((or (eq (sequence-start-event-style event) :flow)
             (sequence-end-event-p next)) :flow)
        (t :seq)))

(defun %emit-sequence-start-frame (state event next)
  (let ((context (emitter-frame-state-context state))
        (stack (emitter-frame-state-stack state)))
    (if (and stack (member (caar stack) '(:map :map-after-explicit-key))
             (evenp (cdar stack)) (eq (sequence-start-event-style event) :block))
        (progn (unless (emitter-context-line-start context) (%emit-newline context))
               (%emit-text context "? "))
        (progn (when (and (eq (caar stack) :map-after-explicit-key)
                          (not (emitter-context-line-start context)))
                 (%emit-newline context))
               (%frame-start-value state event)))
    (when (and stack (eq (caar stack) :map) (oddp (cdar stack))
               (eq (emitter-frame-state-last-key-style state) :double-quoted))
      (%emit-newline context))
    (%emit-prefix event context)
    (push (cons (%frame-kind state event next) 0)
          (emitter-frame-state-stack state))
    (when (and (cdr (emitter-frame-state-stack state))
               (eq (caar (cdr (emitter-frame-state-stack state)))
                   :map-after-explicit-key))
      (setf (caar (cdr (emitter-frame-state-stack state))) :map))
    (when (%frame-flow-p state) (%emit-text context "["))))

(defun %emit-mapping-start-frame (state event next)
  (let* ((context (emitter-frame-state-context state))
         (stack (emitter-frame-state-stack state))
         (key-p (and stack (%frame-map-p state) (evenp (cdar stack)))))
    (%frame-start-value state)
    (when (and stack (eq (caar stack) :map) (oddp (cdar stack))
             (eq (mapping-start-event-style event) :block)
             (not (emitter-context-line-start context)))
      (%emit-newline context))
    (%emit-prefix event context)
    (push (cons (if (or (and (eq (mapping-start-event-style event) :flow)
                               (or key-p (%frame-flow-p state)))
                            (mapping-end-event-p next)) :flow-map :map)
                0) (emitter-frame-state-stack state))
    (when (%frame-flow-p state) (%emit-text context "{"))))

(defun %emit-sequence-end-frame (state)
  (let ((frame (pop (emitter-frame-state-stack state)))
        (context (emitter-frame-state-context state)))
    (when (eq (car frame) :flow) (%emit-text context "]"))
    (when (emitter-frame-state-stack state)
      (incf (cdar (emitter-frame-state-stack state)))
      (when (eq (car frame) :explicit-key-seq)
        (setf (caar (emitter-frame-state-stack state)) :map-after-explicit-key)))))
(defun %emit-mapping-end-frame (state)
  (let ((frame (pop (emitter-frame-state-stack state)))
        (context (emitter-frame-state-context state)))
    (when (eq (car frame) :flow-map) (%emit-text context "}"))
    (when (emitter-frame-state-stack state)
      (incf (cdar (emitter-frame-state-stack state))))))
