;;;; src/emitter.lisp
(in-package #:yaml-kit)

(defun %event-style (event)
  (let ((value (scalar-event-value event))
        (requested (scalar-event-style event)))
    (if (eq requested :plain)
        (if (%plain-safe-p value)
            :plain
            (if (find #\Newline value) :double-quoted :single-quoted))
        requested)))

(defun emit-event-stream (events stream &key (indent 2) (width 80)
                                      (explicit-document-start nil))
  (declare (ignore width))
  (let ((context (make-emitter-context stream indent width))
        (stack nil) (first-document t))
    (dolist (event events)
      (cond
        ((stream-start-event-p event))
        ((stream-end-event-p event)
         (unless (emitter-context-line-start context) (%emit-newline context)))
        ((document-start-event-p event)
         (when (or explicit-document-start
                   (document-start-event-explicit-p event))
           (when (not first-document) (%emit-newline context))
           (%emit-text context "---") (%emit-newline context))
         (setf first-document nil))
        ((document-end-event-p event)
         (unless (emitter-context-line-start context) (%emit-newline context)))
        ((scalar-event-p event)
         (let ((style (%event-style event)))
           (when stack
             (let ((frame (car stack)))
               (cond
                 ((eq (car frame) :map)
                  (if (oddp (cdr frame))
                      (%emit-text context ": ")
                      (when (and (not (emitter-context-line-start context))
                                 (eq (car frame) :map))
                        (%emit-newline context))))
                 ((and (eq (car frame) :seq)
                       (emitter-context-line-start context))
                  (%emit-text context (make-string (* (1- (length stack)) indent)
                                                   :initial-element #\Space))
                  (%emit-text context "- ")))))
           (when (scalar-event-anchor event)
             (%emit-text context (format nil "&~a " (scalar-event-anchor event))))
           (when (scalar-event-tag event)
             (%emit-text context (format nil "~a " (scalar-event-tag event))))
           (%emit-text context (%scalar-text (scalar-event-value event) style))
           (when stack (incf (cdr (car stack))))))
        ((alias-event-p event)
         (%emit-text context (format nil "*~a" (alias-event-anchor event)))
         (when stack (incf (cdr (car stack)))))
        ((sequence-start-event-p event)
         (when stack
           (let ((frame (car stack)))
             (if (eq (car frame) :map)
                 (if (oddp (cdr frame)) (%emit-text context ": ")
                     (%emit-newline context))
                 (when (emitter-context-line-start context)
                   (%emit-text context (make-string (* (length stack) indent)
                                                    :initial-element #\Space)))))
         (push (cons (if (eq (sequence-start-event-style event) :flow) :flow :seq) 0)
               stack)
         (when (eq (caar stack) :flow) (%emit-text context "[")))
        ((mapping-start-event-p event)
         (when stack
           (let ((frame (car stack)))
             (if (eq (car frame) :map)
                 (if (oddp (cdr frame)) (%emit-text context ": ")
                     (%emit-newline context))
                 (when (emitter-context-line-start context)
                   (%emit-text context (make-string (* (length stack) indent)
                                                    :initial-element #\Space)))))
         (push (cons (if (eq (mapping-start-event-style event) :flow) :flow :map) 0)
               stack)
         (when (eq (caar stack) :flow) (%emit-text context "{")))
        ((sequence-end-event-p event)
         (let ((frame (pop stack)))
           (when (eq (car frame) :flow) (%emit-text context "]"))
           (when stack (incf (cdr (car stack))))))
        ((mapping-end-event-p event)
         (let ((frame (pop stack)))
           (when (eq (car frame) :flow) (%emit-text context "}"))
           (when stack (incf (cdr (car stack))))))))
    stream))))
