;;;; src/emitter-scalars.lisp
(in-package #:yaml-kit)

(defparameter +yaml-indicator-characters+ "-?:,[]{}#&*!|>'\"%@`")

(defun %plain-safe-p (value &key flow)
  (and (plusp (length value))
       (not (find (char value 0) +yaml-indicator-characters+ :test #'char=))
       (not (member (char value (1- (length value))) '(#\Space #\Tab)))
       (not (find #\Newline value))
       (not (find #\Return value))
       (not (search ": " value))
       (not (search " #" value))
       (or (not flow)
           (not (find-if (lambda (character)
                           (find character ",[]{}" :test #'char=)) value)))
       (eq (if (fboundp '%core-resolve)
               (funcall #'%core-resolve value)
               :str)
           :str)))

(defun %scalar-style (value requested flow width)
  (let ((style (if (eq requested :plain)
                   (if (%plain-safe-p value :flow flow) :plain :single-quoted)
                   requested)))
    (cond ((and (eq style :single-quoted) (find #\Newline value)) :double-quoted)
          ((and (eq style :plain) (find #\Newline value)) :literal)
          ((and (eq style :single-quoted) (> (length value) width)) :folded)
          (t style))))

(defun %hex-digit (value) (schar "0123456789ABCDEF" value))

(defun %write-hex-escape (stream prefix code digits)
  (write-string prefix stream)
  (loop for shift downfrom (* 4 (1- digits)) to 0 by 4
        do (write-char (%hex-digit (logand #xf (ash code (- shift)))) stream)))

(defun %write-double-quoted (value stream)
  (write-char #\" stream)
  (loop for character across value
        for code fixnum = (char-code character)
        do (case character
             (#\Null (write-string "\\0" stream)) (#\Bell (write-string "\\a" stream))
             (#\Backspace (write-string "\\b" stream)) (#\Tab (write-string "\\t" stream))
             (#\Newline (write-string "\\n" stream)) (#\Vt (write-string "\\v" stream))
             (#\Page (write-string "\\f" stream)) (#\Return (write-string "\\r" stream))
             (#\Escape (write-string "\\e" stream)) (#\" (write-string "\\\"" stream))
             (#\\ (write-string "\\\\" stream))
             (t (cond ((= code #x85) (write-string "\\N" stream))
                      ((= code #xa0) (write-string "\\_" stream))
                      ((= code #x2028) (write-string "\\L" stream))
                      ((= code #x2029) (write-string "\\P" stream))
                      ((or (< code #x20) (= code #x7f)) (%write-hex-escape stream "\\x" code 2))
                      ((or (<= #xd800 code #xdfff) (and (> code #x7e) (< code #xa0)))
                       (%write-hex-escape stream "\\u" code 4))
                      (t (write-char character stream))))))
  (write-char #\" stream))

(defun %write-single-quoted (value stream)
  (write-char #\' stream)
  (loop for character across value do
    (write-char character stream)
    (when (char= character #\') (write-char #\' stream)))
  (write-char #\' stream))

(defun %write-block-scalar (value stream folded)
  (write-char (if folded #\> #\|) stream)
  (write-char #\Newline stream)
  (loop for start = 0 then (1+ end)
        for end = (position #\Newline value :start start)
        do (when (> start (length value)) (return))
           (when (and folded (< start (length value))) (write-char #\Space stream))
           (when end (write-string value stream :start start :end end)
             (write-char #\Newline stream))
           (unless end (when (< start (length value)) (write-string value stream :start start))
             (write-char #\Newline stream) (return))))

(defun %write-scalar (value style stream)
  (case style
    (:plain (write-string value stream))
    (:single-quoted (%write-single-quoted value stream))
    (:double-quoted (%write-double-quoted value stream))
    (:literal (%write-block-scalar value stream nil))
    (:folded (%write-block-scalar value stream t))))
