(in-package #:yaml-kit)

(defun %emit-stream-start-event (event state lookahead) (declare (ignore event state lookahead)))
(defun %emit-stream-end-event (event state lookahead)
  (declare (ignore event lookahead))
  (let ((context (emitter-frame-state-context state)))
    (unless (emitter-context-line-start context) (%emit-newline context))))
(defun %emit-document-start-event (event state lookahead)
  (%emit-document-directives event (emitter-frame-state-context state))
  (let ((context (emitter-frame-state-context state)))
    (when (or (emitter-frame-state-explicit state) (document-start-event-explicit-p event)
              (document-start-event-version event) (document-start-event-tag-directives event)
              (and (not (emitter-frame-state-suppress state))
                   (document-end-event-p (car lookahead)))
              (and (not (emitter-frame-state-suppress state))
                   (or (sequence-start-event-p (car lookahead))
                       (mapping-start-event-p (car lookahead)))
                   (or (and (sequence-start-event-p (car lookahead))
                            (sequence-end-event-p (cadr lookahead)))
                       (and (mapping-start-event-p (car lookahead))
                            (mapping-end-event-p (cadr lookahead))))))
      (when (and (not (emitter-frame-state-first-document state))
                 (not (emitter-context-line-start context))) (%emit-newline context))
      (%emit-text context "---")
      (if (or (and (scalar-event-p (car lookahead))
                   (plusp (length (scalar-event-value (car lookahead)))))
              (alias-event-p (car lookahead))
              (and (sequence-start-event-p (car lookahead))
                   (eq (sequence-start-event-style (car lookahead)) :flow)))
          (%emit-text context " ") (%emit-newline context))))
  (setf (emitter-frame-state-first-document state) nil))
(defun %emit-document-end-event (event state lookahead)
  (declare (ignore lookahead))
  (let ((context (emitter-frame-state-context state)))
    (when (document-end-event-explicit-p event)
      (unless (emitter-context-line-start context) (%emit-newline context))
      (%emit-text context "...") (%emit-newline context))
    (unless (emitter-context-line-start context) (%emit-newline context))))

(defun %emit-scalar-event (event state lookahead)
  (let* ((event (%normalize-scalar-event event))
         (context (emitter-frame-state-context state)) (value (scalar-event-value event))
         (empty (zerop (length value)))
         (key-p (and (emitter-frame-state-stack state) (%frame-map-p state)
                     (evenp (cdar (emitter-frame-state-stack state)))))
         (style (if (and (or key-p (and (%frame-map-p state)
                                        (oddp (cdar (emitter-frame-state-stack state)))))
                         (eq (scalar-event-style event) :plain) (plusp (length value))
                         (or (char= (char value 0) #\?)
                             (and (char= (char value 0) #\:) (> (length value) 1)
                                  (not (%yaml-blank-p (char value 1))))))
                    (if (member value '("true" "True" "TRUE" "false" "False" "FALSE"
                                        "null" "Null" "NULL" "~" "1.5" "0x1F")
                                      :test #'string=)
                        :single-quoted
                        :plain)
                    (%scalar-style value (scalar-event-style event) (%frame-flow-p state)
                                   (scalar-event-tag event)))))
    (when (and (string= (or (scalar-event-tag event) "") "tag:yaml.org,2002:str")
               (member value '("true" "True" "TRUE" "false" "False" "FALSE"
                               "null" "Null" "NULL" "~" "1.5" "0x1F")
                       :test #'string=))
      (setf style :single-quoted))
    (%frame-start-value state event) (%emit-prefix event context)
    (unless (and empty (eq (scalar-event-style event) :plain) (null (scalar-event-tag event)))
      (%write-scalar value style context
                     (* (max 1 (length (emitter-frame-state-stack state)))
                        (emitter-frame-state-indent state))
                     (not (some (lambda (candidate)
                                  (and (document-end-event-p candidate)
                                       (document-end-event-explicit-p candidate)))
                                lookahead))))
    (when (emitter-frame-state-stack state) (incf (cdar (emitter-frame-state-stack state))))
    (when key-p (setf (emitter-frame-state-last-key-style state) style))))
(defun %emit-alias-event (event state lookahead)
  (declare (ignore lookahead))
  (%frame-start-value state) (%emit-text (emitter-frame-state-context state) "*")
  (%emit-text (emitter-frame-state-context state) (alias-event-anchor event))
  (when (emitter-frame-state-stack state) (incf (cdar (emitter-frame-state-stack state)))))
(defun %emit-sequence-start-event (event state lookahead)
  (%emit-sequence-start-frame state event (car lookahead)))
(defun %emit-mapping-start-event (event state lookahead)
  (%emit-mapping-start-frame state event (car lookahead)))
(defun %emit-sequence-end-event (event state lookahead)
  (declare (ignore event lookahead)) (%emit-sequence-end-frame state))
(defun %emit-mapping-end-event (event state lookahead)
  (declare (ignore event lookahead)) (%emit-mapping-end-frame state))
