;;;; src/emitter.lisp
(in-package #:yaml-kit)

(defun %emit-prefix (event context)
  (when (or (scalar-event-p event)
            (sequence-start-event-p event)
            (mapping-start-event-p event))
    (let ((anchor (cond ((scalar-event-p event) (scalar-event-anchor event))
                        ((sequence-start-event-p event) (sequence-start-event-anchor event))
                        (t (mapping-start-event-anchor event)))))
      (when anchor
        (%emit-text context "&")
        (%emit-text context anchor)
        (%emit-text context " ")))
    (let ((tag (cond ((scalar-event-p event) (scalar-event-tag event))
                     ((sequence-start-event-p event) (sequence-start-event-tag event))
                     (t (mapping-start-event-tag event)))))
      (when (and tag
                 (not (member tag '("tag:yaml.org,2002:int"
                                    "tag:yaml.org,2002:float"
                                    "tag:yaml.org,2002:bool"
                                    "tag:yaml.org,2002:null") :test #'string=)))
        (%emit-text context tag)
        (%emit-text context " ")))))

(defun %emit-document-directives (event context)
  (when (document-start-event-version event)
    (%emit-text context "%YAML ")
    (%emit-text context (document-start-event-version event))
    (%emit-newline context))
  (dolist (directive (document-start-event-tag-directives event))
    (%emit-text context "%TAG ")
    (%emit-text context (car directive))
    (%emit-text context " ")
    (%emit-text context (cdr directive))
    (%emit-newline context)))

(defun emit-event-stream (events stream &key (indent 2) (width 80)
                                      (explicit-document-start nil))
  (let ((context (make-emitter-context stream indent width))
        (stack nil)
        (first-document t))
    (labels ((flow-p () (and stack (member (caar stack) '(:flow :flow-map))))
             (map-p () (and stack (member (caar stack) '(:map :flow-map))))
             (separator ()
               (when (and stack (flow-p) (plusp (cdar stack)))
                 (%emit-text context ", ")))
             (start-value ()
               (when stack
                 (let ((frame (car stack)))
                   (cond
                     ((map-p)
                      (if (oddp (cdr frame))
                          (%emit-text context ": ")
                          (if (flow-p)
                              (separator)
                              (progn
                                (unless (emitter-context-line-start context)
                                  (%emit-newline context))
                                (%emit-text context
                                            (make-string (* (1- (length stack)) indent)
                                                         :initial-element #\Space))))))
                     ((emitter-context-line-start context)
                      (%emit-text context
                                  (make-string (* (1- (length stack)) indent)
                                               :initial-element #\Space))
                      (%emit-text context "- "))
                     ((flow-p)
                      (separator))
                     (t
                      (%emit-newline context)
                      (%emit-text context
                                  (make-string (* (1- (length stack)) indent)
                                               :initial-element #\Space))
                      (%emit-text context "- ")))))))
      (loop for remaining on events
            for event = (car remaining)
            do (cond
          ((stream-start-event-p event))
          ((stream-end-event-p event)
           (unless (emitter-context-line-start context) (%emit-newline context)))
          ((document-start-event-p event)
           (%emit-document-directives event context)
           (when (or explicit-document-start
                     (document-start-event-explicit-p event)
                     (document-start-event-version event)
                     (document-start-event-tag-directives event))
             (when (and (not first-document)
                        (not (emitter-context-line-start context)))
               (%emit-newline context))
             (%emit-text context "---")
             (if (and (cdr remaining)
                      (or (scalar-event-p (cadr remaining))
                          (alias-event-p (cadr remaining))
                          (and (sequence-start-event-p (cadr remaining))
                               (eq (sequence-start-event-style (cadr remaining)) :flow))
                          (and (mapping-start-event-p (cadr remaining))
                               (eq (mapping-start-event-style (cadr remaining)) :flow))))
                 (%emit-text context " ")
                 (%emit-newline context)))
           (setf first-document nil))
          ((document-end-event-p event)
           (when (document-end-event-explicit-p event)
             (unless (emitter-context-line-start context) (%emit-newline context))
             (%emit-text context "...")
             (%emit-newline context))
           (unless (emitter-context-line-start context) (%emit-newline context)))
          ((scalar-event-p event)
           (start-value)
           (%emit-prefix event context)
           (%emit-text
            context
            (with-output-to-string (scalar-stream)
              (%write-scalar (scalar-event-value event)
                             (%scalar-style (scalar-event-value event)
                                            (scalar-event-style event)
                                            (flow-p) width
                                            (scalar-event-tag event))
                             scalar-stream
                             (* (1+ (length stack)) indent))))
           (when stack (incf (cdr (car stack)))))
          ((alias-event-p event)
           (start-value)
           (%emit-text context "*")
           (%emit-text context (alias-event-anchor event))
           (when stack (incf (cdr (car stack)))))
          ((sequence-start-event-p event)
           (start-value)
           (%emit-prefix event context)
           (push (cons (if (or (eq (sequence-start-event-style event) :flow)
                               (and (cdr remaining)
                                    (sequence-end-event-p (cadr remaining))))
                           :flow
                           :seq)
                       0)
                 stack)
           (when (flow-p) (%emit-text context "[")))
          ((mapping-start-event-p event)
           (start-value)
           (%emit-prefix event context)
           (push (cons (if (or (eq (mapping-start-event-style event) :flow)
                               (and (cdr remaining)
                                    (mapping-end-event-p (cadr remaining))))
                           :flow-map
                           :map)
                       0)
                 stack)
           (when (flow-p) (%emit-text context "{")))
          ((sequence-end-event-p event)
           (let ((frame (pop stack)))
             (when (eq (car frame) :flow) (%emit-text context "]"))
             (when stack (incf (cdr (car stack))))))
          ((mapping-end-event-p event)
           (let ((frame (pop stack)))
             (when (eq (car frame) :flow-map) (%emit-text context "}"))
             (when stack (incf (cdr (car stack))))))))
    stream)))
