(in-package #:yaml-kit)

(defun %float-positive-infinity ()
  #+sbcl sb-kernel::double-float-positive-infinity
  #-sbcl (error "cl-yaml-kit requires SBCL"))

(defun %float-negative-infinity ()
  #+sbcl sb-kernel::double-float-negative-infinity
  #-sbcl (error "cl-yaml-kit requires SBCL"))

(defun %float-nan ()
  #+sbcl (sb-kernel:make-double-float #x7ff80000 1)
  #-sbcl (error "cl-yaml-kit requires SBCL"))

(defun %float-infinity-p (value)
  #+sbcl (sb-ext:float-infinity-p value)
  #-sbcl nil)

(defun %float-nan-p (value)
  #+sbcl (sb-ext:float-nan-p value)
  #-sbcl nil)

(defun %parse-yaml-float (text &optional mark)
  (let* ((lower (string-downcase text)) (length (length lower)))
    (cond
      ((string= lower ".nan")
       (%float-nan))
      ((member lower '(".inf" "+.inf") :test #'string=)
       (%float-positive-infinity))
      ((string= lower "-.inf") (%float-negative-infinity))
      (t
       (let ((index 0) (sign 1d0) (digits 0) (fraction 0) (exponent 0)
             (exponent-sign 1) (saw-digit nil) (saw-dot nil) (integer-value 0) (value 0d0))
         (when (and (< index length) (member (char lower index) '(#\+ #\-) :test #'char=))
           (when (char= (char lower index) #\-) (setf sign -1d0)) (incf index))
         (loop while (and (< index length) (digit-char-p (char lower index) 10))
               do (let ((digit (digit-char-p (char lower index) 10)))
                    (setf saw-digit t integer-value (+ (* integer-value 10) digit)
                          value (+ (* value 10d0) (coerce digit 'double-float))))
                  (incf digits) (incf index))
         (when (and (< index length) (char= (char lower index) #\.))
           (setf saw-dot t) (incf index)
           (loop while (and (< index length) (digit-char-p (char lower index) 10))
                 do (let ((digit (digit-char-p (char lower index) 10)))
                      (setf saw-digit t integer-value (+ (* integer-value 10) digit)
                            value (+ (* value 10d0) (coerce digit 'double-float))))
                    (incf fraction) (incf index)))
         (when (and (< index length) (char= (char lower index) #\e))
           (incf index)
           (when (and (< index length) (member (char lower index) '(#\+ #\-) :test #'char=))
             (when (char= (char lower index) #\-) (setf exponent-sign -1)) (incf index))
           (unless (and (< index length) (digit-char-p (char lower index) 10))
             (%float-error mark))
           (loop while (and (< index length) (digit-char-p (char lower index) 10))
                 do (setf exponent (min 1000 (+ (* exponent 10)
                                                (digit-char-p (char lower index) 10)))) (incf index)))
         (unless (and saw-digit (or (not saw-dot) saw-digit) (= index length))
           (%float-error mark))
         (let ((scale (- (* exponent-sign exponent) fraction)))
           (cond ((zerop value) 0d0)
                 ((> scale 400) (if (minusp sign) (%float-negative-infinity)
                                    (%float-positive-infinity)))
                 ((< scale -400) (* sign 0d0))
                 (t (handler-case
                        (let ((exact (and (<= (+ digits fraction) 1000)
                                          (if (>= scale 0) (* integer-value (expt 10 scale)) (/ integer-value (expt 10 (- scale)))))))
                          (coerce (* sign (or exact (* value (expt 10d0 scale))))
                                  'double-float))
                      (floating-point-overflow ()
                        (if (minusp sign) (%float-negative-infinity)
                            (%float-positive-infinity))))))))))))

(defun %float-error (mark)
  (signal-yaml-compose-error :mark mark :cause "invalid scalar value"))
