;;;; src/parser.lisp
(in-package #:yaml-kit)

(defun reader-emit (handler event)
  (funcall handler event))

(defun reader-document-marker-p (state marker)
  (and (loop for i below (length marker)
             always (char= (or (reader-peek state i) #\Null)
                           (char marker i)))
       (reader-line-boundary-p state (length marker))))

(defun reader-directive-field (line start)
  (let ((position start) (length (length line)) (fields nil))
    (loop while (< position length) do
      (loop while (and (< position length)
                       (member (char line position) '(#\Space #\Tab)))
            do (incf position))
      (when (< position length)
        (let ((begin position))
          (loop while (and (< position length)
                           (not (member (char line position) '(#\Space #\Tab))))
                do (incf position))
          (push (subseq line begin position) fields))))
    (nreverse fields)))

(defun reader-read-directive (state)
  (let ((start (reader-state-position state)))
    (reader-skip-line state)
    (let* ((line (subseq (reader-state-text state) start
                         (reader-state-position state)))
           (fields (reader-directive-field line 1)))
      (when (null fields) (reader-parse-error state "empty directive"))
      (cond
        ((string= (first fields) "YAML")
         (unless (= (length fields) 2)
           (reader-parse-error state "invalid YAML directive"))
         (list :yaml (second fields)))
        ((string= (first fields) "TAG")
         (unless (= (length fields) 3)
           (reader-parse-error state "invalid TAG directive"))
         (list :tag (second fields) (third fields)))
        (t (reader-parse-error state "unknown directive"))))))

(defun reader-expand-tag (tag directives)
  (when tag
    (cond
      ((and (> (length tag) 2) (char= (char tag 0) #\!)
            (char= (char tag 1) #\<))
       (if (char= (char tag (1- (length tag))) #\>)
           (subseq tag 2 (1- (length tag)))
           tag))
      ((and (> (length tag) 1) (string= (subseq tag 0 2) "!!"))
       (concatenate 'string "tag:yaml.org,2002:" (subseq tag 2)))
      ((and (> (length tag) 1) (char= (char tag 0) #\!))
       (let* ((bang (position #\! tag :start 1))
              (end (if bang (1+ bang) 1))
              (handle (subseq tag 0 end))
              (prefix (cdr (assoc handle directives :test #'string=))))
         (if prefix (concatenate 'string prefix (subseq tag end)) tag)))
      (t tag))))

(defun reader-normalize-event (event directives)
  (cond
    ((typep event 'sequence-start-event)
     (setf (sequence-start-event-tag event)
           (reader-expand-tag (sequence-start-event-tag event) directives)))
    ((typep event 'mapping-start-event)
     (setf (mapping-start-event-tag event)
           (reader-expand-tag (mapping-start-event-tag event) directives)))
    ((typep event 'scalar-event)
     (setf (scalar-event-tag event)
           (reader-expand-tag (scalar-event-tag event) directives))))
  event)

(defun reader-skip-blank-lines (state)
  (loop
    (when (reader-eof-p state) (return))
    (let ((save (reader-state-position state))
          (line (reader-state-line state))
          (column (reader-state-column state)))
      (loop while (member (reader-peek state) '(#\Space #\Tab))
            do (reader-advance state))
      (cond
        ((reader-eof-p state) (return))
        ((or (yaml-line-break-p (reader-peek state))
             (char= (reader-peek state) #\#))
         (reader-skip-line state))
        (t
         (setf (reader-state-position state) save
               (reader-state-line state) line
               (reader-state-column state) column)
         (return))))))

(defun map-events (handler input &key (max-input-length 104857600)
                                      (max-depth 256)
                                      (max-scalar-length 16777216))
  (let ((directives nil)
        (version nil)
        (text (reader-input-string input)))
    (labels ((emit (event)
               (when (typep event 'document-start-event)
                 (setf (document-start-event-version event) version
                       (document-start-event-tag-directives event)
                       (copy-list directives)))
               (funcall handler (reader-normalize-event event directives))))
      (let ((state (make-reader-state% :text text :handler #'emit
                                       :max-input-length max-input-length
                                       :max-depth max-depth
                                       :max-scalar-length max-scalar-length)))
    (when (> (length text) max-input-length) (error 'yaml-resource-limit-error))
    (when (and (reader-peek state) (char= (reader-peek state) (code-char #xfeff)))
      (reader-advance state))
    (reader-send state (make-stream-start-event :start-mark (reader-mark state)
                                                :end-mark (reader-mark state)))
    (loop
      (reader-skip-blank-lines state)
      (when (reader-eof-p state) (return))
      (setf directives nil version nil)
      (loop while (and (reader-line-start-p state)
                       (char= (or (reader-peek state) #\Null) #\%)) do
        (let ((directive (reader-read-directive state)))
          (case (first directive)
            (:yaml (setf version (second directive)))
            (:tag (push (cons (second directive) (third directive)) directives))))
        (reader-skip-blank-lines state))
      (let ((explicit (reader-document-marker-p state "---")))
        (when explicit
          (dotimes (i 3) (declare (ignore i)) (reader-advance state))
          (reader-comment-or-break state))
        (reader-send state (make-document-start-event :start-mark (reader-mark state)
                                                      :end-mark (reader-mark state)
                                                      :explicit-p explicit))
        (reader-skip-blank-lines state)
        (unless (or (reader-eof-p state)
                    (reader-document-marker-p state "..."))
          (reader-block-node state (reader-current-indent state)))
        (reader-skip-blank-lines state)
        (when (reader-document-marker-p state "...")
          (dotimes (i 3) (declare (ignore i)) (reader-advance state))
          (reader-comment-or-break state)
          (setf explicit t))
        (reader-send state (make-document-end-event :start-mark (reader-mark state)
                                                    :end-mark (reader-mark state)
                                                    :explicit-p explicit))))
    (reader-send state (make-stream-end-event :start-mark (reader-mark state)
                                              :end-mark (reader-mark state)))
    nil))))

(defun parse-events (input &rest keys)
  (let ((events nil))
    (apply #'map-events (lambda (event) (push event events)) input keys)
    (nreverse events)))
