;;;; src/parser.lisp
(in-package #:yaml-kit)

(defun reader-emit (handler event)
  (funcall handler event))

(defun map-events (handler input &key (max-input-length 104857600)
                                      (max-depth 256)
                                      (max-scalar-length 16777216))
  (let* ((text (reader-input-string input))
         (state (make-reader-state% :text text :handler handler
                                    :max-input-length max-input-length
                                    :max-depth max-depth
                                    :max-scalar-length max-scalar-length)))
    (when (> (length text) max-input-length) (error 'yaml-resource-limit-error))
    (reader-send state (make-stream-start-event :start-mark (reader-mark state)
                                                :end-mark (reader-mark state)))
    (loop
      (reader-skip-blank-lines state)
      (when (reader-eof-p state) (return))
      (let ((explicit nil))
        (when (and (char= (or (reader-peek state) #\Null) #\-)
                   (char= (or (reader-peek state 1) #\Null) #\-)
                   (char= (or (reader-peek state 2) #\Null) #\-))
          (setf explicit t) (dotimes (i 3) (declare (ignore i)) (reader-advance state))
          (reader-skip-line state))
        (reader-send state (make-document-start-event :start-mark (reader-mark state)
                                                      :end-mark (reader-mark state)
                                                      :explicit-p explicit))
        (reader-skip-blank-lines state)
        (unless (or (reader-eof-p state)
                    (and (char= (or (reader-peek state) #\Null) #\.)
                         (char= (or (reader-peek state 1) #\Null) #\.)
                         (char= (or (reader-peek state 2) #\Null) #\.)))
          (reader-block-node state (reader-current-indent state)))
        (reader-skip-blank-lines state)
        (when (and (char= (or (reader-peek state) #\Null) #\.)
                   (char= (or (reader-peek state 1) #\Null) #\.)
                   (char= (or (reader-peek state 2) #\Null) #\.))
          (dotimes (i 3) (declare (ignore i)) (reader-advance state))
          (reader-skip-line state)
          (setf explicit t))
        (reader-send state (make-document-end-event :start-mark (reader-mark state)
                                                    :end-mark (reader-mark state)
                                                    :explicit-p explicit))))
    (reader-send state (make-stream-end-event :start-mark (reader-mark state)
                                              :end-mark (reader-mark state)))
    nil))

(defun parse-events (input &rest keys)
  (let ((events nil))
    (apply #'map-events (lambda (event) (push event events)) input keys)
    (nreverse events)))
