;;;; src/scanner-scalars.lisp
(in-package #:yaml-kit)

(defun reader-hex-value (state count)
  (let ((value 0))
    (loop repeat count do
      (let ((character (reader-peek state)))
        (unless (and character (digit-char-p character 16))
          (reader-parse-error state "invalid hexadecimal escape"))
        (setf value (+ (* value 16) (digit-char-p character 16)))
        (reader-advance state)))
    value))

(defun reader-valid-code-point-p (value)
  (or (= value #x9) (= value #xa) (= value #xd)
      (<= #x20 value #x7e) (= value #x85)
      (<= #xa0 value #xd7ff) (<= #xe000 value #xfffd)
      (<= #x10000 value #x10ffff)))

(defun reader-quoted-code-point (state count)
  (let ((value (reader-hex-value state count)))
    (unless (and (reader-valid-code-point-p value) (< value char-code-limit))
      (reader-parse-error state "invalid Unicode code point"))
    (code-char value)))

(defun reader-skip-quoted-continuation (state)
  (loop
    (loop while (yaml-whitespace-p (reader-peek state)) do (reader-advance state))
    (if (yaml-line-break-p (reader-peek state))
        (reader-advance state)
        (return))))

(defun reader-skip-quoted-line-break (state)
  (when (yaml-line-break-p (reader-peek state))
    (reader-advance state)
    (reader-skip-quoted-continuation state)))

(defun reader-decode-double-quoted (state)
  (let ((out (make-array 32 :element-type 'character :adjustable t :fill-pointer 0)))
    (unless (char= (reader-peek state) #\") (reader-parse-error state "expected double quote"))
    (reader-advance state)
    (loop
      (when (reader-eof-p state) (reader-parse-error state "unterminated double-quoted scalar"))
      (let ((character (reader-peek state)))
        (cond
          ((char= character #\") (reader-advance state) (return (coerce out 'simple-string)))
          ((char= character #\\)
           (reader-advance state)
           (let ((escape (reader-peek state)))
             (when (null escape) (reader-parse-error state "unterminated escape"))
             (reader-advance state)
             (case escape
               (#\0 (vector-push-extend (code-char 0) out)) (#\a (vector-push-extend (code-char 7) out))
               (#\b (vector-push-extend (code-char 8) out)) (#\t (vector-push-extend #\Tab out))
               (#\n (vector-push-extend #\Newline out)) (#\v (vector-push-extend (code-char 11) out))
               (#\f (vector-push-extend (code-char 12) out)) (#\r (vector-push-extend #\Return out))
               (#\e (vector-push-extend (code-char 27) out)) (#\Space (vector-push-extend #\Space out))
               (#\" (vector-push-extend #\" out)) (#\/ (vector-push-extend #\/ out))
               (#\\ (vector-push-extend #\\ out)) (#\N (vector-push-extend (code-char #x85) out))
               (#\_ (vector-push-extend (code-char #xa0) out)) (#\L (vector-push-extend (code-char #x2028) out))
               (#\P (vector-push-extend (code-char #x2029) out))
               (#\x (vector-push-extend (reader-quoted-code-point state 2) out))
               (#\u (vector-push-extend (reader-quoted-code-point state 4) out))
               (#\U (vector-push-extend (reader-quoted-code-point state 8) out))
               ((#\Newline #\Return) (reader-skip-quoted-continuation state))
               (otherwise (reader-parse-error state "unknown escape")))))
          ((yaml-line-break-p character)
           (reader-skip-quoted-line-break state)
           (unless (or (zerop (fill-pointer out))
                       (char= (aref out (1- (fill-pointer out))) #\Space))
             (vector-push-extend #\Space out)))
          (t (vector-push-extend character out) (reader-advance state)))))))
