;;;; src/scanner.lisp
(in-package #:yaml-kit)

(defun scan-space-p (c)
  (and c (or (char= c #\Space) (char= c #\Tab))))

(defun scan-line-end-p (c)
  (or (null c) (char= c #\Newline) (char= c #\Return)))

(defun scan-newline (scanner)
  (when (char= (or (scan-peek scanner) #\Null) #\Return) (scan-advance scanner))
  (when (char= (or (scan-peek scanner) #\Null) #\Newline) (scan-advance scanner)))

(defun scan-skip-comment (scanner)
  (loop until (scan-line-end-p (scan-peek scanner)) do (scan-advance scanner)))

(defun scan-indent (scanner)
  (let ((count 0))
    (loop while (char= (or (scan-peek scanner) #\Null) #\Space)
          do (incf count) (scan-advance scanner))
    (when (char= (or (scan-peek scanner) #\Null) #\Tab)
      (scan-error scanner "tab character must not be used for indentation"))
    count))

(defun scan-mapping-line-p (scanner)
  (let* ((index (scanner-position scanner))
         (text (scanner-text scanner))
         (end (or (position #\Newline text :start index) (length text))))
    (loop for i fixnum from index below end
          when (and (char= (char text i) #\:)
                    (or (= (1+ i) end)
                        (scan-space-p (char text (1+ i)))))
            do (return t)
          finally (return nil))))

(defun scan-emit-indentation (scanner indent)
  (let ((old (car (scanner-indents scanner))))
    (cond
      ((or (null old) (> indent old))
       (let ((kind (cond
                     ((char= (or (scan-peek scanner) #\Null) #\-)
                      :block-sequence-start)
                     ((scan-mapping-line-p scanner)
                      :block-mapping-start))))
         (when kind
           (push indent (scanner-indents scanner))
           (scan-push-token scanner kind (scan-mark scanner) (scan-mark scanner)))))
      ((< indent old)
       (loop while (and (scanner-indents scanner)
                        (< indent (car (scanner-indents scanner))))
             do (pop (scanner-indents scanner))
                (scan-push-token scanner :block-end (scan-mark scanner) (scan-mark scanner)))))))

(defun scan-read-name (scanner kind)
  (let ((start (scan-mark scanner)) (begin (scanner-position scanner)))
    (loop while (and (scan-peek scanner)
                     (not (scan-space-p (scan-peek scanner)))
                     (not (scan-line-end-p (scan-peek scanner)))
                     (not (yaml-flow-indicator-p (scan-peek scanner))))
          do (scan-advance scanner))
    (when (= begin (scanner-position scanner)) (scan-error scanner "expected name"))
    (scan-push-token scanner kind start (scan-mark scanner)
                     :value (subseq (scanner-text scanner) begin (scanner-position scanner)))))

(defun scan-read-plain (scanner)
  (let ((start (scan-mark scanner)) (begin (scanner-position scanner)))
    (loop while (and (scan-peek scanner)
                     (not (scan-line-end-p (scan-peek scanner)))
                     (not (scan-space-p (scan-peek scanner)))
                     (not (yaml-flow-indicator-p (scan-peek scanner)))
                     (not (and (char= (scan-peek scanner) #\:)
                               (or (null (scan-peek scanner 1))
                                   (scan-space-p (scan-peek scanner 1))))))
          do (scan-advance scanner))
    (when (= begin (scanner-position scanner)) (scan-error scanner "expected scalar"))
    (scan-push-token scanner :scalar start (scan-mark scanner)
                     :value (subseq (scanner-text scanner) begin (scanner-position scanner))
                     :style :plain)))

(defun scan-read-quoted (scanner quote)
  (let ((start (scan-mark scanner))
        (out (make-array 32 :element-type 'character :adjustable t :fill-pointer 0)))
    (scan-advance scanner)
    (loop
      (when (scan-eof-p scanner) (scan-error scanner "unterminated quoted scalar"))
      (let ((c (scan-peek scanner)))
        (cond
          ((char= c quote)
           (scan-advance scanner)
           (if (and (char= quote #\') (char= (or (scan-peek scanner) #\Null) #\'))
               (progn (vector-push-extend quote out) (scan-advance scanner))
               (return (scan-push-token scanner :scalar start (scan-mark scanner)
                                         :value (coerce out 'simple-string)
                                         :style (if (char= quote #\') :single-quoted :double-quoted)))))
          ((and (char= quote #\") (char= c #\\))
           (scan-advance scanner)
           (let ((e (scan-peek scanner)))
             (when (null e) (scan-error scanner "unterminated escape"))
             (scan-advance scanner)
             (case e
               (#\0 (vector-push-extend (code-char 0) out)) (#\a (vector-push-extend (code-char 7) out))
               (#\b (vector-push-extend (code-char 8) out)) (#\t (vector-push-extend #\Tab out))
               (#\n (vector-push-extend #\Newline out)) (#\r (vector-push-extend #\Return out))
               (#\e (vector-push-extend (code-char 27) out)) (#\  (vector-push-extend #\Space out))
               (#\" (vector-push-extend #\" out)) (#\/ (vector-push-extend #\/ out))
               (#\\ (vector-push-extend #\\ out))
               (otherwise (scan-error scanner "unknown escape")))))
          ((scan-line-end-p c) (scan-error scanner "quoted scalar cannot contain a raw line break"))
          (t (vector-push-extend c out) (scan-advance scanner)))))))

(defun scan-read-tag (scanner)
  (let ((start (scan-mark scanner)))
    (scan-advance scanner)
    (if (char= (or (scan-peek scanner) #\Null) #\<)
        (progn
          (scan-advance scanner)
          (let ((begin (scanner-position scanner)))
            (loop until (char= (or (scan-peek scanner) #\Null) #\>) do
              (when (scan-eof-p scanner) (scan-error scanner "unterminated verbatim tag"))
              (scan-advance scanner))
            (scan-push-token scanner :tag start (scan-mark scanner) :handle ""
                             :suffix (subseq (scanner-text scanner) begin (scanner-position scanner)))
            (scan-advance scanner)))
        (let ((begin (1- (scanner-position scanner))))
          (loop while (and (scan-peek scanner) (not (scan-space-p (scan-peek scanner)))
                           (not (yaml-flow-indicator-p (scan-peek scanner)))) do (scan-advance scanner))
          (let* ((raw (subseq (scanner-text scanner) begin (scanner-position scanner)))
                 (split (position #\! raw :start 1))
                 (handle (if split (subseq raw 0 (1+ split)) "!!"))
                 (suffix (if split (subseq raw (1+ split)) (subseq raw 1))))
            (when (string= raw "!") (setf handle "" suffix "!"))
            (scan-push-token scanner :tag start (scan-mark scanner) :handle handle :suffix suffix))))))

(defun scan-read-directive (scanner)
  (let ((start (scan-mark scanner)))
    (scan-advance scanner)
    (let ((begin (scanner-position scanner)))
      (loop while (and (scan-peek scanner) (not (scan-space-p (scan-peek scanner)))
                       (not (scan-line-end-p (scan-peek scanner)))) do (scan-advance scanner))
      (let ((name (subseq (scanner-text scanner) begin (scanner-position scanner))))
        (cond
          ((string= name "YAML")
           (loop while (scan-space-p (scan-peek scanner)) do (scan-advance scanner))
           (let ((a (scanner-position scanner)))
             (loop while (and (scan-peek scanner) (digit-char-p (scan-peek scanner))) do (scan-advance scanner))
             (let ((major (parse-integer (scanner-text scanner) :start a :end (scanner-position scanner))))
               (unless (char= (or (scan-peek scanner) #\Null) #\.) (scan-error scanner "invalid YAML directive"))
               (scan-advance scanner)
               (let ((b (scanner-position scanner)))
                 (loop while (and (scan-peek scanner) (digit-char-p (scan-peek scanner))) do (scan-advance scanner))
                 (scan-push-token scanner :version-directive start (scan-mark scanner)
                                  :major major :minor (parse-integer (scanner-text scanner) :start b :end (scanner-position scanner)))))))
          ((string= name "TAG")
           (loop while (scan-space-p (scan-peek scanner)) do (scan-advance scanner))
           (let ((a (scanner-position scanner)))
             (loop while (and (scan-peek scanner) (not (scan-space-p (scan-peek scanner)))) do (scan-advance scanner))
             (let ((handle (subseq (scanner-text scanner) a (scanner-position scanner))))
               (loop while (scan-space-p (scan-peek scanner)) do (scan-advance scanner))
               (let ((b (scanner-position scanner)))
                 (loop while (and (scan-peek scanner) (not (scan-line-end-p (scan-peek scanner)))) do (scan-advance scanner))
                 (scan-push-token scanner :tag-directive start (scan-mark scanner) :handle handle
                                  :value (subseq (scanner-text scanner) b (scanner-position scanner)))))))
          (t (scan-skip-comment scanner)))))))

(defun scan-tokenize (scanner)
  (let ((mark (scan-mark scanner))) (scan-push-token scanner :stream-start mark mark))
  (loop until (scan-eof-p scanner) do
    (let ((indent (scan-indent scanner)))
      (cond
        ((scan-line-end-p (scan-peek scanner)) (scan-newline scanner))
        ((char= (or (scan-peek scanner) #\Null) #\#) (scan-skip-comment scanner) (scan-newline scanner))
        (t
         (scan-emit-indentation scanner indent)
         (let ((c (scan-peek scanner)) (start (scan-mark scanner)))
           (cond
             ((char= c #\%) (scan-read-directive scanner))
             ((and (char= c #\-) (char= (or (scan-peek scanner 1) #\Null) #\-)
                   (char= (or (scan-peek scanner 2) #\Null) #\-))
              (dotimes (i 3) (scan-advance scanner))
              (scan-push-token scanner :document-start start (scan-mark scanner)))
             ((and (char= c #\.) (char= (or (scan-peek scanner 1) #\Null) #\.)
                   (char= (or (scan-peek scanner 2) #\Null) #\.))
              (dotimes (i 3) (scan-advance scanner))
              (scan-push-token scanner :document-end start (scan-mark scanner)))
             ((char= c #\-) (scan-advance scanner) (scan-push-token scanner :block-entry start (scan-mark scanner)))
             ((char= c #\?) (scan-advance scanner) (scan-push-token scanner :key start (scan-mark scanner)))
             ((char= c #\:) (scan-advance scanner) (scan-push-token scanner :value start (scan-mark scanner)))
             ((char= c #\,) (scan-advance scanner) (scan-push-token scanner :flow-entry start (scan-mark scanner)))
             ((char= c #\[) (incf (scanner-flow-level scanner)) (scan-advance scanner) (scan-push-token scanner :flow-sequence-start start (scan-mark scanner)))
             ((char= c #\]) (decf (scanner-flow-level scanner)) (scan-advance scanner) (scan-push-token scanner :flow-sequence-end start (scan-mark scanner)))
             ((char= c #\{) (incf (scanner-flow-level scanner)) (scan-advance scanner) (scan-push-token scanner :flow-mapping-start start (scan-mark scanner)))
             ((char= c #\}) (decf (scanner-flow-level scanner)) (scan-advance scanner) (scan-push-token scanner :flow-mapping-end start (scan-mark scanner)))
             ((char= c #\&) (scan-advance scanner) (scan-read-name scanner :anchor))
             ((char= c #\*) (scan-advance scanner) (scan-read-name scanner :alias))
             ((char= c #\!) (scan-read-tag scanner))
             ((member c '(#\" #\'))
              (let ((value (scan-quoted-scalar scanner)))
                (scan-push-token scanner :scalar start (scan-mark scanner)
                                 :value value
                                 :style (if (char= c #\') :single-quoted :double-quoted))))
             ((member c '(#\| #\>))
              (scan-advance scanner)
              (scan-push-token scanner :scalar start (scan-mark scanner)
                               :value (scan-block-scalar scanner indent
                                                          (if (char= c #\|) :literal :folded))
                               :style (if (char= c #\|) :literal :folded)))
             (t
              (let ((value (scan-plain-scalar scanner (> (scanner-flow-level scanner) 0))))
                (if (zerop (length value))
                    (scan-error scanner "expected scalar")
                    (scan-push-token scanner :scalar start (scan-mark scanner)
                                     :value value :style :plain)))))
           (loop while (scan-space-p (scan-peek scanner)) do (scan-advance scanner))
           (when (char= (or (scan-peek scanner) #\Null) #\#) (scan-skip-comment scanner))
           (when (scan-line-end-p (scan-peek scanner)) (scan-newline scanner)))))))
  (loop while (scanner-indents scanner) do
    (pop (scanner-indents scanner))
    (scan-push-token scanner :block-end (scan-mark scanner) (scan-mark scanner)))
  (let ((mark (scan-mark scanner))) (scan-push-token scanner :stream-end mark mark))
  scanner)
