;;;; src/scanner.lisp
(in-package #:yaml-kit)

(defun reader-utf8-string (octets)
  (let ((out (make-array (length octets) :element-type 'character :adjustable t :fill-pointer 0))
        (i 0))
    (loop while (< i (length octets)) do
      (let ((b (aref octets i)))
        (cond
          ((< b 128) (vector-push-extend (code-char b) out) (incf i))
          ((and (<= #xc2 b #xdf) (< (+ i 1) (length octets)))
           (vector-push-extend (code-char (+ (ash (logand b #x1f) 6) (logand (aref octets (+ i 1)) #x3f))) out) (incf i 2))
          ((and (<= #xe0 b #xef) (< (+ i 2) (length octets)))
           (vector-push-extend (code-char (+ (ash (logand b #xf) 12) (ash (logand (aref octets (+ i 1)) #x3f) 6) (logand (aref octets (+ i 2)) #x3f))) out) (incf i 3))
          ((and (<= #xf0 b #xf4) (< (+ i 3) (length octets)))
           (vector-push-extend (code-char (+ (ash (logand b 7) 18) (ash (logand (aref octets (+ i 1)) #x3f) 12) (ash (logand (aref octets (+ i 2)) #x3f) 6) (logand (aref octets (+ i 3)) #x3f))) out) (incf i 4))
          (t (error 'yaml-parse-error :context "invalid UTF-8 input")))))
    (coerce out 'simple-string)))

(defun reader-fixed-width-string (octets width little-endian-p)
  (let ((out (make-array (floor (length octets) width) :element-type 'character
                         :adjustable t :fill-pointer 0)))
    (loop for i from 0 below (- (length octets) (1- width)) by width do
      (let ((value 0))
        (loop for j from 0 below width do
          (let ((shift (* 8 (if little-endian-p j (- width j 1)))))
            (setf value (logior value (ash (aref octets (+ i j)) shift)))))
        (vector-push-extend (code-char value) out)))
    (coerce out 'simple-string)))

(defun reader-input-string (input)
  (typecase input
    (string (coerce input 'simple-string))
    (stream (with-output-to-string (out) (loop for c = (read-char input nil nil) while c do (write-char c out))))
    ((vector (unsigned-byte 8))
     (let* ((start (cond ((and (>= (length input) 3) (= (aref input 0) #xef) (= (aref input 1) #xbb) (= (aref input 2) #xbf)) 3)
                         ((and (>= (length input) 4) (= (aref input 0) 0) (= (aref input 1) 0) (= (aref input 2) #xfe) (= (aref input 3) #xff)) 4)
                         ((and (>= (length input) 4) (= (aref input 0) #xff) (= (aref input 1) #xfe) (= (aref input 2) 0) (= (aref input 3) 0)) 4)
                         ((and (>= (length input) 2) (= (aref input 0) #xfe) (= (aref input 1) #xff)) 2)
                         ((and (>= (length input) 2) (= (aref input 0) #xff) (= (aref input 1) #xfe)) 2)
                         (t 0)))
            (bytes (subseq input start)))
       ;; cl-codec-kit is the production decoder; this fallback keeps the reader
       ;; loadable in a bare ASDF image used by small downstream test runners.
       (cond
         ((and (find-package "CL-CODEC-KIT") (fboundp (find-symbol "OCTETS-TO-STRING" "CL-CODEC-KIT")))
          (funcall (find-symbol "OCTETS-TO-STRING" "CL-CODEC-KIT") bytes :encoding :utf-8 :errorp t))
         ((and (>= (length input) 4) (= (aref input 0) 0) (= (aref input 1) 0) (= (aref input 2) #xfe) (= (aref input 3) #xff))
          (reader-fixed-width-string bytes 4 nil))
         ((and (>= (length input) 4) (= (aref input 0) #xff) (= (aref input 1) #xfe) (= (aref input 2) 0) (= (aref input 3) 0))
          (reader-fixed-width-string bytes 4 t))
         ((and (>= (length input) 2) (= (aref input 0) #xfe) (= (aref input 1) #xff))
          (reader-fixed-width-string bytes 2 nil))
         ((and (>= (length input) 2) (= (aref input 0) #xff) (= (aref input 1) #xfe))
          (reader-fixed-width-string bytes 2 t))
         (t (reader-utf8-string bytes)))))
    (otherwise (error 'yaml-parse-error :context "invalid YAML input"))))

(defun reader-emit (state constructor &rest arguments)
  (apply (or (reader-state-handler state) (lambda (event) (declare (ignore event)))) constructor
         (append (list :start-mark (reader-mark state) :end-mark (reader-mark state)) arguments)))

(defun reader-send (state event)
  (funcall (reader-state-handler state) event))

(defun reader-skip-space (state)
  (loop while (member (reader-peek state) '(#\Space #\Tab)) do (reader-advance state)))

(defun reader-comment-or-break (state)
  (reader-skip-space state)
  (when (char= (or (reader-peek state) #\Null) #\#) (reader-skip-line state))
  (when (and (not (reader-eof-p state)) (yaml-line-break-p (reader-peek state))) (reader-skip-line state)))

(defun reader-colon-here-p (state)
  (let ((character (reader-peek state)))
    (and (char= character #\:) (or (null (reader-peek state 1))
                                    (yaml-whitespace-p (reader-peek state 1))
                                    (yaml-flow-indicator-p (reader-peek state 1))))))

(defun reader-read-property (state)
  (let ((anchor nil) (tag nil))
    (loop
      (reader-skip-space state)
      (cond
        ((char= (or (reader-peek state) #\Null) #\&)
         (reader-advance state)
         (let ((start (reader-state-position state)))
           (loop while (and (reader-peek state) (not (yaml-whitespace-p (reader-peek state)))) do (reader-advance state))
           (setf anchor (subseq (reader-state-text state) start (reader-state-position state)))))
        ((char= (or (reader-peek state) #\Null) #\!)
         (let ((start (reader-state-position state)))
           (reader-advance state)
           (when (char= (or (reader-peek state) #\Null) #\<)
             (reader-advance state)
             (loop
               (when (reader-eof-p state)
                 (reader-parse-error state "unterminated verbatim tag"))
               (when (char= (reader-peek state) #\>) (return))
               (reader-advance state))
             (reader-advance state))
           (loop while (and (reader-peek state) (not (yaml-whitespace-p (reader-peek state)))) do (reader-advance state))
           (setf tag (subseq (reader-state-text state) start (reader-state-position state)))))
        (t (return (values anchor tag)))))))

(defun reader-scalar-event (state value style anchor tag start)
  (when (> (length value) (reader-state-max-scalar-length state)) (error 'yaml-resource-limit-error))
  (make-scalar-event :start-mark start :end-mark (reader-mark state) :anchor anchor :tag tag
                     :value (coerce value 'simple-string) :style style
                     :plain-implicit-p (and (eq style :plain) (null tag))
                     :quoted-implicit-p (and (not (eq style :plain)) (null tag))))

(defun reader-flow-node (state)
  (reader-skip-space state)
  (let ((start (reader-mark state)))
    (incf (reader-state-depth state)) (reader-limit-depth state)
    (unwind-protect
         (multiple-value-bind (anchor tag) (reader-read-property state)
           (reader-skip-space state)
           (let ((character (reader-peek state)))
             (cond
               ((char= character #\*)
                (reader-advance state) (let ((p (reader-state-position state)))
                                        (loop while (and (reader-peek state) (not (yaml-whitespace-p (reader-peek state))) (not (yaml-flow-indicator-p (reader-peek state)))) do (reader-advance state))
                                        (reader-send state (make-alias-event :start-mark start :end-mark (reader-mark state) :anchor (subseq (reader-state-text state) p (reader-state-position state))))))
               ((char= character #\[) (reader-flow-sequence state start anchor tag))
               ((char= character #\{) (reader-flow-mapping state start anchor tag))
               ((char= character #\") (reader-send state (reader-scalar-event state (reader-decode-double-quoted state) :double-quoted anchor tag start)))
               ((char= character #\') (reader-send state (reader-scalar-event state (reader-single-quoted state) :single-quoted anchor tag start)))
               (t (reader-send state (reader-scalar-event state (reader-plain-value state t) :plain anchor tag start))))))
      (decf (reader-state-depth state)))))

(defun reader-flow-sequence (state start anchor tag)
  (reader-advance state) (reader-send state (make-sequence-start-event :start-mark start :end-mark (reader-mark state) :anchor anchor :tag tag :implicit-p nil :style :flow))
  (loop
    (reader-skip-space state)
    (when (char= (or (reader-peek state) #\Null) #\]) (reader-advance state) (return))
    (reader-flow-node state) (reader-skip-space state)
    (cond ((char= (or (reader-peek state) #\Null) #\,) (reader-advance state))
          ((char= (or (reader-peek state) #\Null) #\]) (reader-advance state) (return))
          (t (reader-parse-error state "expected comma or closing bracket"))))
  (reader-send state (make-sequence-end-event :start-mark start :end-mark (reader-mark state))))

(defun reader-flow-mapping (state start anchor tag)
  (reader-advance state) (reader-send state (make-mapping-start-event :start-mark start :end-mark (reader-mark state) :anchor anchor :tag tag :implicit-p nil :style :flow))
  (loop
    (reader-skip-space state)
    (when (char= (or (reader-peek state) #\Null) #\}) (reader-advance state) (return))
    (reader-flow-node state) (reader-skip-space state)
    (unless (char= (or (reader-peek state) #\Null) #\:) (reader-parse-error state "expected mapping colon"))
    (reader-advance state) (reader-skip-space state)
    (if (member (reader-peek state) '(#\, #\}))
        (reader-send state (make-scalar-event :start-mark (reader-mark state) :end-mark (reader-mark state) :value "" :style :plain :plain-implicit-p t))
        (reader-flow-node state))
    (reader-skip-space state)
    (cond ((char= (or (reader-peek state) #\Null) #\,) (reader-advance state))
          ((char= (or (reader-peek state) #\Null) #\}) (reader-advance state) (return))
          (t (reader-parse-error state "expected comma or closing brace"))))
  (reader-send state (make-mapping-end-event :start-mark start :end-mark (reader-mark state))))

(defun reader-line-has-mapping-colon-p (state)
  (let ((i (reader-state-position state)) (quote nil) (depth 0) (text (reader-state-text state)))
    (loop while (and (< i (length text)) (not (yaml-line-break-p (char text i))))
          for c = (char text i)
          do (cond ((and (null quote) (member c '(#\' #\"))) (setf quote c))
                   ((and quote (char= quote c)) (setf quote nil))
                   ((and (null quote) (member c '(#\[ #\{))) (incf depth))
                   ((and (null quote) (member c '(#\] #\}))) (decf depth))
                   ((and (null quote) (zerop depth) (char= c #\:)
                         (or (= (1+ i) (length text)) (yaml-whitespace-p (char text (1+ i))))) (return t)))
          do (incf i))))

(defun reader-single-quoted (state)
  (let ((out (make-array 32 :element-type 'character :adjustable t :fill-pointer 0)))
    (reader-advance state)
    (loop
      (when (reader-eof-p state) (reader-parse-error state "unterminated single-quoted scalar"))
      (let ((c (reader-peek state)))
        (reader-advance state)
        (if (char= c #\')
            (if (char= (or (reader-peek state) #\Null) #\')
                (progn (vector-push-extend #\' out) (reader-advance state))
                (return (coerce out 'simple-string)))
            (vector-push-extend c out))))))

(defun reader-plain-value (state flow-p)
  (let ((out (make-array 64 :element-type 'character :adjustable t :fill-pointer 0)))
    (loop while (and (reader-peek state) (not (yaml-line-break-p (reader-peek state)))
                     (not (and flow-p (member (reader-peek state) '(#\, #\] #\}))))
                     (not (reader-colon-here-p state)))
          do (vector-push-extend (reader-peek state) out) (reader-advance state))
    (loop while (and (> (fill-pointer out)) (member (aref out (1- (fill-pointer out))) '(#\Space #\Tab)))
          do (decf (fill-pointer out)))
    (coerce out 'simple-string)))

(defun reader-block-scalar (state parent-indent style)
  (reader-skip-line state)
  (let ((lines nil) (content-indent nil))
    (loop while (not (reader-eof-p state)) do
      (let ((line-start (reader-state-position state)) (indent 0))
        (loop while (char= (or (reader-peek state) #\Null) #\Space) do (incf indent) (reader-advance state))
        (when (<= indent parent-indent)
          (setf (reader-state-position state) line-start (reader-state-column state) 1)
          (return))
        (unless content-indent (setf content-indent indent))
        (let ((begin (+ line-start (min indent content-indent))))
          (loop while (and (reader-peek state) (not (yaml-line-break-p (reader-peek state)))) do (reader-advance state))
          (push (subseq (reader-state-text state) begin (reader-state-position state)) lines)
          (reader-skip-line state))))
    (setf lines (nreverse lines))
    (let ((value (with-output-to-string (out)
                   (loop for line in lines for first = t then nil do
                     (unless first (write-char #\Newline out)) (write-string line out)))))
      (when lines (setf value (concatenate 'string value "\n")))
      (when (eq style :folded) (setf value (substitute #\Space #\Newline value)))
      value)))

(defun reader-empty-scalar (state)
  (reader-send state (make-scalar-event :start-mark (reader-mark state) :end-mark (reader-mark state)
                                        :value "" :style :plain :plain-implicit-p t)))

(defun reader-inline-node (state)
  (reader-skip-space state)
  (let ((start (reader-mark state)))
    (multiple-value-bind (anchor tag) (reader-read-property state)
      (reader-skip-space state)
      (let ((c (reader-peek state)))
        (cond
          ((char= c #\[) (reader-flow-sequence state start anchor tag))
          ((char= c #\{) (reader-flow-mapping state start anchor tag))
          ((char= c #\*)
           (reader-advance state) (let ((p (reader-state-position state)))
                                    (loop while (and (reader-peek state) (not (yaml-whitespace-p (reader-peek state)))) do (reader-advance state))
                                    (reader-send state (make-alias-event :start-mark start :end-mark (reader-mark state) :anchor (subseq (reader-state-text state) p (reader-state-position state))))))
          ((char= c #\") (reader-send state (reader-scalar-event state (reader-decode-double-quoted state) :double-quoted anchor tag start)))
          ((char= c #\') (reader-send state (reader-scalar-event state (reader-single-quoted state) :single-quoted anchor tag start)))
          ((member c '(#\| #\>))
           (reader-advance state) (reader-send state (reader-scalar-event state (reader-block-scalar state (reader-current-indent state) (if (char= c #\|) :literal :folded)) (if (char= c #\|) :literal :folded) anchor tag start)))
          (t (reader-send state (reader-scalar-event state (reader-plain-value state nil) :plain anchor tag start))))))))

(defun reader-block-node (state indent)
  (reader-skip-space state)
  (let ((start (reader-mark state)))
    (cond
      ((and (char= (or (reader-peek state) #\Null) #\-) (or (null (reader-peek state 1)) (yaml-whitespace-p (reader-peek state 1))))
       (incf (reader-state-depth state)) (reader-limit-depth state)
       (reader-send state (make-sequence-start-event :start-mark start :end-mark start :style :block :implicit-p t))
       (loop
         (unless (and (= (reader-current-indent state) indent) (char= (or (reader-peek state) #\Null) #\-) (or (null (reader-peek state 1)) (yaml-whitespace-p (reader-peek state 1)))) (return))
         (reader-advance state) (reader-skip-space state)
         (if (or (reader-eof-p state) (yaml-line-break-p (reader-peek state)))
             (progn (reader-skip-line state) (reader-skip-blank-lines state) (if (> (reader-current-indent state) indent) (reader-block-node state (reader-current-indent state)) (reader-empty-scalar state)))
             (reader-inline-node state))
         (reader-comment-or-break state) (reader-skip-blank-lines state))
       (reader-send state (make-sequence-end-event :start-mark start :end-mark (reader-mark state)))
       (decf (reader-state-depth state)))
      ((reader-line-has-mapping-colon-p state)
       (incf (reader-state-depth state)) (reader-limit-depth state)
       (reader-send state (make-mapping-start-event :start-mark start :end-mark start :style :block :implicit-p t))
       (loop
         (unless (and (= (reader-current-indent state) indent) (reader-line-has-mapping-colon-p state)) (return))
         (reader-inline-node state) (reader-skip-space state)
         (unless (char= (or (reader-peek state) #\Null) #\:) (reader-parse-error state "expected mapping colon"))
         (reader-advance state) (reader-skip-space state)
         (if (or (reader-eof-p state) (yaml-line-break-p (reader-peek state)))
             (progn (reader-skip-line state) (reader-skip-blank-lines state) (if (> (reader-current-indent state) indent) (reader-block-node state (reader-current-indent state)) (reader-empty-scalar state)))
             (reader-inline-node state))
         (reader-comment-or-break state) (reader-skip-blank-lines state))
       (reader-send state (make-mapping-end-event :start-mark start :end-mark (reader-mark state)))
       (decf (reader-state-depth state)))
      (t (reader-inline-node state)))))
