(in-package #:yaml-kit)

(defun stale-simple-keys (s)
  (dolist (key (scanner-simple-keys s))
    (when (and (simple-key-possible key)
               (let ((mark (simple-key-mark key)))
                 (or (< (mark-line mark) (scanner-line s))
                     (< (+ (mark-offset mark) +max-simple-key-length+) (scanner-pos s)))))
      (when (simple-key-required key)
        (sc-error s "while scanning a simple key" (simple-key-mark key) "could not find expected ':'"))
      (setf (simple-key-possible key) nil)))
  t)

(defun save-simple-key (s)
  (when (scanner-simple-key-allowed s)
    (remove-simple-key s)
    (let ((key (first (scanner-simple-keys s))))
      (when key
        (setf (simple-key-possible key) t
              (simple-key-required key) (and (zerop (scanner-flow-level s))
                                             (= (scanner-indent s) (scanner-column s)))
              (simple-key-token-number key)
              (+ (scanner-tokens-parsed s)
                 (- (fill-pointer (scanner-tokens s)) (scanner-tokens-head s)))
              (simple-key-mark key) (sc-mark s)))))
  t)

(defun remove-simple-key (s)
  (let ((key (first (scanner-simple-keys s))))
    (when (and key (simple-key-possible key))
      (when (simple-key-required key)
        (sc-error s "while scanning a simple key" (simple-key-mark key) "could not find expected ':'"))
      (setf (simple-key-possible key) nil)))
  t)

(defun increase-flow-level (s)
  (push (make-simple-key) (scanner-simple-keys s))
  (incf (scanner-flow-level s))
  t)

(defun decrease-flow-level (s)
  (when (plusp (scanner-flow-level s))
    (decf (scanner-flow-level s))
    (pop (scanner-simple-keys s)))
  t)

(defun roll-indent (s column number kind mark &optional additional-tokens)
  (when (and (zerop (scanner-flow-level s)) (> column (scanner-indent s)))
    (push (scanner-indent s) (scanner-indents s))
    (setf (scanner-indent s) column)
    (if (= number -1)
        (enqueue-token s (make-scanner-token s kind mark mark))
        (insert-tokens s (- number (scanner-tokens-parsed s))
                       (cons (make-scanner-token s kind mark mark) additional-tokens))))
  t)

(defun unroll-indent (s column)
  (unless (plusp (scanner-flow-level s))
    (loop while (> (scanner-indent s) column)
          do (enqueue-token s (make-scanner-token s :block-end (sc-mark s) (sc-mark s)))
             (setf (scanner-indent s) (pop (scanner-indents s)))))
  t)

(defun scan-to-next-token (s)
  (let ((after-break nil))
    (loop
      (when (and (zerop (scanner-column s)) (sc-bom-p s)) (sc-skip s))
      (loop while (or (sc-space-p s) (sc-tab-p s)) do
        (when (and (zerop (scanner-flow-level s)) (zerop (scanner-column s))
                   (not (= (scanner-indent s) -1)) (sc-tab-p s))
          (sc-error s "while scanning for the next token" (sc-mark s)
                    "found a tab character that violates indentation"))
        (sc-skip s))
      (when (and after-break (plusp (scanner-flow-level s))
                 (< (scanner-column s) (1+ (scanner-indent s))))
        (sc-error s "while scanning for the next token" (sc-mark s)
                  "found a line that is not indented enough to continue the flow collection"))
      (when (sc-check s #\#)
        (loop until (sc-breakz-p s) do (sc-skip s))
        (setf after-break nil))
      (if (sc-break-p s)
          (progn (sc-skip-line s)
                 (when (zerop (scanner-flow-level s))
                   (setf (scanner-simple-key-allowed s) t))
                 (setf after-break t))
          (return t)))))
