;;;; src/scanner-state.lisp
(in-package #:yaml-kit)

(defstruct (simple-key (:constructor make-simple-key ()))
  (possible nil :type boolean)
  (required nil :type boolean)
  (token-number 0 :type fixnum)
  (mark nil :type (or null mark)))

(defstruct (scanner (:constructor %make-scanner (text)))
  (text "" :type (simple-array character (*)) :read-only t)
  (pos 0 :type fixnum)
  (line 0 :type fixnum)
  (column 0 :type fixnum)
  (tokens (make-array 16 :adjustable t :fill-pointer 0) :type vector)
  (tokens-head 0 :type fixnum)
  (tokens-parsed 0 :type fixnum)
  (token-available nil :type boolean)
  (indent -1 :type fixnum)
  (indents nil :type list)
  (simple-key-allowed nil :type boolean)
  (simple-keys nil :type list)
  (flow-level 0 :type fixnum)
  (stream-start-produced nil :type boolean)
  (stream-end-produced nil :type boolean))

(declaim (inline sc-char sc-check sc-mark sc-skip sc-skip-line sc-read
                 sc-read-line sc-hex-value))

(defun sc-char (s &optional (k 0))
  (let ((index (+ (scanner-pos s) k)))
    (if (< index (length (scanner-text s)))
        (char (scanner-text s) index)
        #\Nul)))
(defun sc-check (s char &optional (k 0))
  (char= (sc-char s k) char))
(defun sc-mark (s)
  (make-mark (scanner-line s) (scanner-column s) (scanner-pos s)))
(defun sc-skip (s)
  (unless (sc-z-p s)
    (incf (scanner-pos s))
    (incf (scanner-column s)))
  nil)
(defun sc-skip-line (s)
  (when (sc-check s #\Return) (sc-skip s))
  (when (sc-check s #\Newline) (sc-skip s))
  (incf (scanner-line s))
  (setf (scanner-column s) 0)
  nil)
(defun sc-read (s buffer)
  (vector-push-extend (sc-char s) buffer)
  (sc-skip s)
  buffer)
(defun sc-read-line (s buffer)
  (vector-push-extend #\Newline buffer)
  (sc-skip-line s)
  buffer)
(defun sc-hex-value (s k)
  (or (digit-char-p (sc-char s k) 16)
      (sc-error s "while scanning a hexadecimal value" (sc-mark s)
                "expected a hexadecimal digit")))
(defun sc-error (s context context-mark problem)
  (declare (ignore context-mark))
  (let ((mark (sc-mark s)))
    (error 'yaml-parse-error
         :line (mark-line mark)
         :column (mark-column mark)
         :offset (mark-offset mark)
         :context context
         :message problem)))
(defun make-scan-buffer ()
  (make-array 64 :element-type 'character :adjustable t :fill-pointer 0))
(defun scan-buffer-string (buffer)
  (coerce (subseq buffer 0 (fill-pointer buffer)) 'simple-string))
(defun enqueue-token (s token)
  (vector-push-extend token (scanner-tokens s))
  (setf (scanner-token-available s) t)
  token)
(defun insert-token (s index token)
  (let* ((tokens (scanner-tokens s))
         (absolute (+ (scanner-tokens-head s) index))
         (length (fill-pointer tokens)))
    (vector-push-extend nil tokens)
    (replace tokens tokens :start1 (1+ absolute) :start2 absolute :end2 length)
    (setf (aref tokens absolute) token
          (scanner-token-available s) t)
    token))
(defun make-scanner (text)
  (check-type text (simple-array character (*)))
  (%make-scanner text))
(defun scanner-peek-token (s)
  (when (< (scanner-tokens-head s) (fill-pointer (scanner-tokens s)))
    (aref (scanner-tokens s) (scanner-tokens-head s))))
(defun scanner-next-token (s)
  (let ((token (scanner-peek-token s)))
    (when token
      (incf (scanner-tokens-head s))
      (incf (scanner-tokens-parsed s))
      (when (= (scanner-tokens-head s) (fill-pointer (scanner-tokens s)))
        (setf (scanner-token-available s) nil))
      token)))
