(in-package #:yaml-kit)

(defun scan-uri-escapes (s directive start b)
  (let ((width 0) (octets (make-array 4 :element-type '(unsigned-byte 8)
                                      :adjustable t :fill-pointer 0)))
    (loop while (or (zerop (fill-pointer octets)) (plusp width)) do
      (unless (and (sc-check s #\%) (sc-hex-p s 1) (sc-hex-p s 2))
        (sc-error s (if directive "while parsing a %TAG directive" "while parsing a tag") start
                  "did not find URI escaped octet"))
      (let ((octet (+ (* 16 (sc-hex-value s 1)) (sc-hex-value s 2))))
        (unless (plusp width) (setf width (cond ((zerop (logand octet #x80)) 1)
                                                ((= (logand octet #xe0) #xc0) 2)
                                                ((= (logand octet #xf0) #xe0) 3)
                                                ((= (logand octet #xf8) #xf0) 4)
                                                (t 0))))
        (when (zerop width) (sc-error s "while parsing a tag" start
                                      "found an incorrect leading UTF-8 octet"))
        (when (and (plusp (fill-pointer octets)) (/= (logand octet #xc0) #x80))
          (sc-error s "while parsing a tag" start "found an incorrect trailing UTF-8 octet"))
        (vector-push-extend octet octets) (dotimes (i 3) (sc-skip s)))
      (decf width)
      (when (zerop width) (return)))
    (handler-case
        (loop for character across (cl-codec-kit:octets-to-string octets :encoding :utf-8 :errorp t)
              do (vector-push-extend character b))
      (cl-codec-kit:invalid-leading-byte ()
        (sc-error s "while parsing a tag" start "invalid UTF-8 URI escape"))
      (cl-codec-kit:invalid-continuation-byte ()
        (sc-error s "while parsing a tag" start "invalid UTF-8 URI escape"))
      (cl-codec-kit:overlong-sequence ()
        (sc-error s "while parsing a tag" start "invalid UTF-8 URI escape"))
      (cl-codec-kit:surrogate-code-point ()
        (sc-error s "while parsing a tag" start "invalid UTF-8 URI escape"))
      (cl-codec-kit:code-point-too-large ()
        (sc-error s "while parsing a tag" start "invalid UTF-8 URI escape"))
      (cl-codec-kit:truncated-sequence ()
        (sc-error s "while parsing a tag" start "invalid UTF-8 URI escape")))))
