;;;; src/scanner-scalars.lisp
(in-package #:yaml-kit)

(defun reader-hex-value (state count)
  (let ((value 0))
    (loop repeat count do
      (let ((character (reader-peek state)))
        (unless (and character (digit-char-p character 16))
          (reader-parse-error state "invalid hexadecimal escape"))
        (setf value (+ (* value 16) (digit-char-p character 16)))
        (reader-advance state)))
    value))

(defun reader-valid-code-point-p (value)
  (or (= value #x9) (= value #xa) (= value #xd)
      (<= #x20 value #x7e) (= value #x85)
      (<= #xa0 value #xd7ff) (<= #xe000 value #xfffd)
      (<= #x10000 value #x10ffff)))

(defun reader-quoted-code-point (state count)
  (let ((value (reader-hex-value state count)))
    (unless (and (reader-valid-code-point-p value) (< value char-code-limit))
      (reader-parse-error state "invalid Unicode code point"))
    (code-char value)))

(defun reader-skip-quoted-continuation (state)
  (loop
    (loop while (yaml-whitespace-p (reader-peek state)) do (reader-advance state))
    (if (yaml-line-break-p (reader-peek state))
        (reader-advance state)
        (return))))

(defun reader-skip-quoted-line-break (state)
  (when (yaml-line-break-p (reader-peek state))
    (reader-advance state)
    (reader-skip-quoted-continuation state)))

(defun reader-decode-double-quoted (state)
  (let ((out (make-array 32 :element-type 'character :adjustable t :fill-pointer 0)))
    (unless (char= (reader-peek state) #\") (reader-parse-error state "expected double quote"))
    (reader-advance state)
    (loop
      (when (reader-eof-p state) (reader-parse-error state "unterminated double-quoted scalar"))
      (let ((character (reader-peek state)))
        (cond
          ((char= character #\") (reader-advance state) (return (coerce out 'simple-string)))
          ((char= character #\\)
           (reader-advance state)
           (let ((escape (reader-peek state)))
             (when (null escape) (reader-parse-error state "unterminated escape"))
             (reader-advance state)
             (case escape
               (#\0 (vector-push-extend (code-char 0) out)) (#\a (vector-push-extend (code-char 7) out))
               (#\b (vector-push-extend (code-char 8) out)) (#\t (vector-push-extend #\Tab out))
               (#\n (vector-push-extend #\Newline out)) (#\v (vector-push-extend (code-char 11) out))
               (#\f (vector-push-extend (code-char 12) out)) (#\r (vector-push-extend #\Return out))
               (#\e (vector-push-extend (code-char 27) out)) (#\Space (vector-push-extend #\Space out))
               (#\" (vector-push-extend #\" out)) (#\/ (vector-push-extend #\/ out))
               (#\\ (vector-push-extend #\\ out)) (#\N (vector-push-extend (code-char #x85) out))
               (#\_ (vector-push-extend (code-char #xa0) out)) (#\L (vector-push-extend (code-char #x2028) out))
               (#\P (vector-push-extend (code-char #x2029) out))
               (#\x (vector-push-extend (reader-quoted-code-point state 2) out))
               (#\u (vector-push-extend (reader-quoted-code-point state 4) out))
               (#\U (vector-push-extend (reader-quoted-code-point state 8) out))
               ((#\Newline #\Return) (reader-skip-quoted-continuation state))
               (otherwise (reader-parse-error state "unknown escape")))))
          ((yaml-line-break-p character)
           (reader-skip-quoted-line-break state)
           (unless (or (zerop (fill-pointer out))
                       (char= (aref out (1- (fill-pointer out))) #\Space))
             (vector-push-extend #\Space out)))
          (t (vector-push-extend character out) (reader-advance state)))))))

(defun scan-hex-value (state count)
  (let ((value 0))
    (loop repeat count do
      (let ((character (scan-peek state)))
        (unless (and character (digit-char-p character 16))
          (scan-error state "invalid hexadecimal escape"))
        (setf value (+ (* value 16) (digit-char-p character 16)))
        (scan-advance state)))
    value))

(defun scan-valid-code-point-p (value)
  (or (= value #x9) (= value #xa) (= value #xd)
      (<= #x20 value #x7e) (= value #x85)
      (<= #xa0 value #xd7ff) (<= #xe000 value #xfffd)
      (<= #x10000 value #x10ffff)))

(defun scan-quoted-code-point (state count)
  (let ((value (scan-hex-value state count)))
    (unless (and (scan-valid-code-point-p value) (< value char-code-limit))
      (scan-error state "invalid Unicode code point"))
    (code-char value)))

(defun scan-skip-quoted-continuation (state)
  (loop
    (loop while (member (scan-peek state) '(#\Space #\Tab)) do (scan-advance state))
    (if (yaml-line-break-p (or (scan-peek state) #\Null))
        (scan-advance state)
        (return))))

(defun scan-skip-quoted-line-break (state)
  (when (yaml-line-break-p (or (scan-peek state) #\Null))
    (scan-advance state)
    (scan-skip-quoted-continuation state)))

(defun scan-double-quoted (state)
  (let ((out (make-array 32 :element-type 'character :adjustable t :fill-pointer 0)))
    (unless (char= (scan-peek state) #\") (scan-error state "expected double quote"))
    (scan-advance state)
    (loop
      (when (scan-eof-p state) (scan-error state "unterminated double-quoted scalar"))
      (let ((character (scan-peek state)))
        (cond
          ((char= character #\") (scan-advance state) (return (coerce out 'simple-string)))
          ((char= character #\\)
           (scan-advance state)
           (let ((escape (scan-peek state)))
             (when (null escape) (scan-error state "unterminated escape"))
             (scan-advance state)
             (case escape
               (#\0 (vector-push-extend (code-char 0) out)) (#\a (vector-push-extend (code-char 7) out))
               (#\b (vector-push-extend (code-char 8) out)) (#\t (vector-push-extend #\Tab out))
               (#\n (vector-push-extend #\Newline out)) (#\v (vector-push-extend (code-char 11) out))
               (#\f (vector-push-extend (code-char 12) out)) (#\r (vector-push-extend #\Return out))
               (#\e (vector-push-extend (code-char 27) out)) (#\Space (vector-push-extend #\Space out))
               (#\" (vector-push-extend #\" out)) (#\/ (vector-push-extend #\/ out))
               (#\\ (vector-push-extend #\\ out)) (#\N (vector-push-extend (code-char #x85) out))
               (#\_ (vector-push-extend (code-char #xa0) out)) (#\L (vector-push-extend (code-char #x2028) out))
               (#\P (vector-push-extend (code-char #x2029) out))
               (#\x (vector-push-extend (scan-quoted-code-point state 2) out))
               (#\u (vector-push-extend (scan-quoted-code-point state 4) out))
               (#\U (vector-push-extend (scan-quoted-code-point state 8) out))
               ((#\Newline #\Return) (scan-skip-quoted-continuation state))
               (otherwise (scan-error state "unknown escape")))))
          ((yaml-line-break-p character)
           (scan-skip-quoted-line-break state)
           (unless (or (zerop (fill-pointer out))
                       (char= (aref out (1- (fill-pointer out))) #\Space))
             (vector-push-extend #\Space out)))
          (t (vector-push-extend character out) (scan-advance state)))))))

(defun scan-single-quoted (state)
  (let ((out (make-array 32 :element-type 'character :adjustable t :fill-pointer 0)))
    (unless (char= (scan-peek state) #\') (scan-error state "expected single quote"))
    (scan-advance state)
    (loop
      (when (scan-eof-p state) (scan-error state "unterminated single-quoted scalar"))
      (let ((character (scan-peek state)))
        (scan-advance state)
        (if (char= character #\')
            (if (char= (or (scan-peek state) #\Null) #\')
                (progn (vector-push-extend #\' out) (scan-advance state))
                (return (coerce out 'simple-string)))
            (vector-push-extend character out))))))

(defun scan-quoted-scalar (state)
  (case (scan-peek state)
    (#\" (scan-double-quoted state))
    (#\' (scan-single-quoted state))
    (otherwise (scan-error state "expected quoted scalar"))))

(defun scan-plain-scalar (state &optional (flow-p nil))
  (let ((out (make-array 64 :element-type 'character :adjustable t :fill-pointer 0)))
    (loop while (and (scan-peek state) (not (yaml-line-break-p (scan-peek state)))
                     (not (and flow-p (member (scan-peek state) '(#\, #\] #\}))))
                     (not (and (char= (scan-peek state) #\:)
                               (or (null (scan-peek state 1))
                                   (yaml-whitespace-p (scan-peek state 1))
                                   (yaml-flow-indicator-p (scan-peek state 1))))))
          do (vector-push-extend (scan-peek state) out) (scan-advance state))
    (loop while (and (plusp (fill-pointer out))
                     (member (aref out (1- (fill-pointer out))) '(#\Space #\Tab)))
          do (decf (fill-pointer out)))
    (coerce out 'simple-string)))

(defun scan-block-scalar (state parent-indent style)
  (let ((chomping :clip) (indent-indicator nil))
    (loop while (and (scan-peek state) (not (yaml-line-break-p (scan-peek state)))) do
      (let ((character (scan-peek state)))
        (cond
          ((member character '(#\Space #\Tab)) (scan-advance state))
          ((member character '(#\- #\+))
           (when (not (eq chomping :clip)) (scan-error state "duplicate block scalar chomping indicator"))
           (setf chomping (if (char= character #\-) :strip :keep)) (scan-advance state))
          ((digit-char-p character 10)
           (when (or indent-indicator (zerop (digit-char-p character 10)))
             (scan-error state "invalid block scalar indentation indicator"))
           (setf indent-indicator (digit-char-p character 10)) (scan-advance state))
          ((char= character #\#) (loop until (or (scan-eof-p state) (yaml-line-break-p (scan-peek state))) do (scan-advance state)))
          (t (scan-error state "invalid block scalar header")))))
    (when (yaml-line-break-p (or (scan-peek state) #\Null)) (scan-advance state))
    (let ((content-indent (and indent-indicator (+ parent-indent indent-indicator)))
          (lines nil) (saw-break nil))
      (loop while (not (scan-eof-p state)) do
        (let ((line-start (scanner-position state)) (line (scanner-line state))
              (column (scanner-column state)) (indent 0))
          (loop while (char= (or (scan-peek state) #\Null) #\Space)
                do (incf indent) (scan-advance state))
          (let* ((content-start (scanner-position state))
                 (blank-p (or (scan-eof-p state) (yaml-line-break-p (or (scan-peek state) #\Null)))))
            (unless blank-p
              (when (or (and content-indent (< indent content-indent)) (<= indent parent-indent))
                (setf (scanner-position state) line-start (scanner-line state) line
                      (scanner-column state) column) (return))
              (unless content-indent (setf content-indent indent)))
            (let ((begin (if blank-p content-start (+ line-start content-indent))))
              (loop while (and (scan-peek state) (not (yaml-line-break-p (scan-peek state)))) do (scan-advance state))
              (push (subseq (scanner-text state) begin (scanner-position state)) lines)
              (when (yaml-line-break-p (or (scan-peek state) #\Null))
                (setf saw-break t) (scan-advance state))))))
      (let ((value (with-output-to-string (out)
                     (loop for line in (nreverse lines) for first = t then nil
                           do (unless first (write-char (if (eq style :folded) #\Space #\Newline) out))
                              (write-string line out)))))
        (when (and (eq chomping :clip) saw-break) (setf value (concatenate 'string value (string #\Newline))))
        (when (eq chomping :strip)
          (loop while (and (plusp (length value)) (char= (char value (1- (length value))) #\Newline))
                do (setf value (subseq value 0 (1- (length value))))))
        value))))
