;;;; src/scanner.lisp
(in-package #:yaml-kit)

(defun reader-mark (line column offset)
  (make-mark (min 255 (max 0 line)) (min 255 (max 0 column))
             (min 255 (max 0 offset))))

(defun reader-input-string (input)
  (typecase input
    (string (coerce input 'simple-string))
    (stream (with-output-to-string (out)
              (loop for c = (read-char input nil nil) while c do (write-char c out))))
    ((vector (unsigned-byte 8))
     (with-output-to-string (out)
       (loop for b across input do (write-char (code-char b) out))))
    (otherwise (error 'yaml-parse-error :context "invalid YAML input"))))

(defun reader-split-lines (text)
  (coerce (loop with start fixnum = 0
                for i fixnum from 0 to (length text)
                when (or (= i (length text)) (char= (char text i) #\Newline))
                  collect (subseq text start i) and do (setf start (1+ i))) 'vector))

(defun reader-comment-cut (s)
  (loop for i fixnum from 0 below (length s)
        when (and (char= (char s i) #\#)
                  (or (zerop i) (reader-whitespace-p (char s (1- i)))))
          do (return (string-right-trim '(#\Space #\Tab #\Return) (subseq s 0 i)))
        finally (return (string-right-trim '(#\Space #\Tab #\Return) s))))

(defun reader-colon-position (s)
  (loop with quote = nil for i fixnum from 0 below (length s)
        for c = (char s i) do
          (cond ((and (null quote) (member c '(#\' #\"))) (setf quote c))
                ((and quote (char= c quote)) (setf quote nil))
                ((and (null quote) (char= c #\:) (or (= (1+ i) (length s))
                                                       (reader-whitespace-p (char s (1+ i)))))
                 (return i)))))

(defun reader-flow-split (s separator)
  (loop with start fixnum = 0 with depth fixnum = 0 with quote = nil
        for i fixnum from 0 to (length s)
        for c = (when (< i (length s)) (char s i))
        when (or (= i (length s)) (and (null quote) (zerop depth) (char= c separator)))
          collect (string-trim '(#\Space #\Tab) (subseq s start i)) and do (setf start (1+ i))
        do (when (< i (length s))
             (cond ((and (null quote) (member c '(#\' #\"))) (setf quote c))
                   ((and quote (char= c quote)) (setf quote nil))
                   ((and (null quote) (member c '(#\[ #\{))) (incf depth))
                   ((and (null quote) (member c '(#\] #\}))) (decf depth))))))

(defun reader-scalar-event (raw line col offset max-length)
  (let ((text (string-trim '(#\Space #\Tab) raw)) (style :plain) (anchor nil) (tag nil))
    (when (> (length text) max-length) (error 'yaml-resource-limit-error))
    (when (and (> (length text) 0) (char= (char text 0) #\&))
      (let ((p (position-if #'yaml-whitespace-p text)))
        (setf anchor (subseq text 1 (or p (length text)))
              text (string-trim '(#\Space #\Tab) (if p (subseq text p) "")))))
    (when (and (> (length text) 0) (char= (char text 0) #\!))
      (let ((p (position-if #'yaml-whitespace-p text)))
        (setf tag (subseq text 0 (or p (length text)))
              text (string-trim '(#\Space #\Tab) (if p (subseq text p) "")))))
    (cond
      ((and (>= (length text) 2) (char= (char text 0) #\') (char= (char text (1- (length text))) #\'))
       (setf style :single-quoted text (subseq text 1 (1- (length text)))))
      ((and (>= (length text) 2) (char= (char text 0) #\") (char= (char text (1- (length text))) #\"))
       (setf style :double-quoted text (reader-decode-double-quoted (subseq text 1 (1- (length text))))))
      ((and (> (length text) 0) (char= (char text 0) #\|)) (setf style :literal text ""))
      ((and (> (length text) 0) (char= (char text 0) #\>)) (setf style :folded text "")))
    (make-scalar-event :start-mark (reader-mark line col offset)
                       :end-mark (reader-mark line (+ col (length raw)) (+ offset (length raw)))
                       :anchor anchor :tag tag :value text :style style
                       :plain-implicit-p (and (eq style :plain) (null tag))
                       :quoted-implicit-p (and (not (eq style :plain)) (null tag)))))

(defun reader-flow-node (raw line col offset depth state)
  (when (> depth (reader-state-max-depth state)) (error 'yaml-resource-limit-error))
  (let ((s (string-trim '(#\Space #\Tab) raw)))
    (cond
      ((and (> (length s) 1) (char= (char s 0) #\*) )
       (list (make-alias-event :start-mark (reader-mark line col offset) :end-mark (reader-mark line col offset)
                               :anchor (subseq s 1))))
      ((and (> (length s) 1) (char= (char s 0) #\[) (char= (char s (1- (length s))) #\]))
       (append (list (make-sequence-start-event :start-mark (reader-mark line col offset) :end-mark (reader-mark line col offset) :style :flow))
               (mapcan (lambda (x) (unless (zerop (length x)) (reader-flow-node x line col offset (1+ depth) state)))
                       (reader-flow-split (subseq s 1 (1- (length s))) #\,))
               (list (make-sequence-end-event :start-mark (reader-mark line col offset) :end-mark (reader-mark line col offset)))))
      ((and (> (length s) 1) (char= (char s 0) #\{) (char= (char s (1- (length s))) #\}))
       (append (list (make-mapping-start-event :start-mark (reader-mark line col offset) :end-mark (reader-mark line col offset) :style :flow))
               (mapcan (lambda (x) (let ((p (reader-colon-position x)))
                                     (unless p (error 'yaml-parse-error :line line :column col :offset offset :context "missing mapping colon"))
                                     (append (reader-flow-node (subseq x 0 p) line col offset (1+ depth) state)
                                             (reader-flow-node (subseq x (1+ p)) line col offset (1+ depth) state))))
                       (reader-flow-split (subseq s 1 (1- (length s))) #\,))
               (list (make-mapping-end-event :start-mark (reader-mark line col offset) :end-mark (reader-mark line col offset)))))
      (t (list (reader-scalar-event s line col offset (reader-state-max-scalar-length state)))))))

(defun map-events (handler input &key (max-input-length 104857600) (max-depth 256) (max-scalar-length 16777216))
  (let* ((text (reader-input-string input))
         (state (make-reader-state% :text text :max-input-length max-input-length
                                    :max-depth max-depth :max-scalar-length max-scalar-length))
         (lines (reader-split-lines text)) (line-no 1) (offset 0) (document-open nil))
    (when (> (length text) max-input-length) (error 'yaml-resource-limit-error))
    (labels ((send (event) (funcall handler event))
             (mark () (reader-mark line-no 1 offset))
             (open-document (&optional explicit)
               (unless document-open
                 (send (make-document-start-event :start-mark (mark) :end-mark (mark) :explicit-p explicit))
                 (setf document-open t)))
             (close-document (&optional explicit)
               (when document-open
                 (send (make-document-end-event :start-mark (mark) :end-mark (mark) :explicit-p explicit))
                 (setf document-open nil))))
      (send (make-stream-start-event :start-mark (mark) :end-mark (mark)))
      (loop for raw across lines do
        (let ((s (reader-comment-cut raw)))
          (unless (zerop (length (string-trim '(#\Space #\Tab) s)))
            (let ((trim (string-trim '(#\Space #\Tab) s)))
              (cond
                ((string= trim "---") (close-document) (open-document t))
                ((string= trim "...") (close-document t))
                ((char= (char trim 0) #\%) nil)
                ((and (> (length trim) 1) (char= (char trim 0) #\-) (yaml-whitespace-p (char trim 1)))
                 (open-document)
                 (send (make-sequence-start-event :start-mark (mark) :end-mark (mark) :style :block))
                 (dolist (e (reader-flow-node (subseq trim 1) line-no 2 offset 0 state)) (send e))
                 (send (make-sequence-end-event :start-mark (mark) :end-mark (mark))))
                ((member (char trim 0) '(#\[ #\{ #\*))
                 (open-document)
                 (dolist (e (reader-flow-node trim line-no 1 offset 0 state)) (send e)))
                ((reader-colon-position trim)
                 (open-document)
                 (let ((p (reader-colon-position trim)))
                   (send (make-mapping-start-event :start-mark (mark) :end-mark (mark) :style :block))
                   (dolist (e (reader-flow-node (subseq trim 0 p) line-no 1 offset 0 state)) (send e))
                   (dolist (e (reader-flow-node (subseq trim (1+ p)) line-no (+ p 2) offset 0 state)) (send e))
                   (send (make-mapping-end-event :start-mark (mark) :end-mark (mark)))))
                (t (open-document) (dolist (e (reader-flow-node trim line-no 1 offset 0 state)) (send e))))))
        (incf line-no) (incf offset (1+ (length raw))))
      (close-document)
      (send (make-stream-end-event :start-mark (mark) :end-mark (mark))))
    nil)))

(defun parse-events (input &key max-input-length max-depth max-scalar-length)
  (let ((result nil))
    (map-events (lambda (event) (push event result)) input :max-input-length (or max-input-length 104857600)
                :max-depth (or max-depth 256) :max-scalar-length (or max-scalar-length 16777216))
    (nreverse result)))
