;;;; src/scanner-state.lisp
(in-package #:yaml-kit)

(defstruct (simple-key (:constructor make-simple-key ())
                       (:copier nil) (:predicate nil))
  (possible nil :type boolean)
  (required nil :type boolean)
  (token-number 0 :type fixnum)
  (mark nil :type (or null mark)))

(defstruct (scanner (:constructor %make-scanner (text))
                    (:copier nil) (:predicate nil))
  (text "" :type (simple-array character (*)) :read-only t)
  (pos 0 :type fixnum)
  (line 0 :type fixnum)
  (column 0 :type fixnum)
  (tokens (make-array 16 :adjustable t :fill-pointer 0) :type vector)
  (scan-buffer (make-scan-buffer) :type vector)
  (scan-leading (make-scan-buffer) :type vector)
  (scan-trailing (make-scan-buffer) :type vector)
  (scan-spaces (make-scan-buffer) :type vector)
  (token-pool nil :type list)
  (recyclable-token nil :type (or null token))
  (tokens-head 0 :type fixnum)
  (tokens-parsed 0 :type fixnum)
  (token-available nil :type boolean)
  (indent -1 :type fixnum)
  (indents nil :type list)
  (simple-key-allowed nil :type boolean)
  (simple-keys nil :type list)
  (flow-level 0 :type fixnum)
  (json-like-node-end nil :type boolean)
  (stream-start-produced nil :type boolean)
  (stream-end-produced nil :type boolean))

(defun make-scanner-token (s kind start-mark end-mark &key value handle suffix style major minor)
  (let ((token (or (pop (scanner-token-pool s))
                   (%make-token kind start-mark end-mark))))
    (setf (token-kind token) kind
          (token-start-mark token) start-mark
          (token-end-mark token) end-mark
          (token-value token) value
          (token-handle token) handle
          (token-suffix token) suffix
          (token-style token) style
          (token-major token) major
          (token-minor token) minor)
    token))

(declaim (inline sc-check sc-mark sc-skip sc-skip-line sc-read
                 sc-read-line sc-hex-value))

(defun sc-char (s &optional (k 0))
  (let ((index (+ (scanner-pos s) k)))
    (if (< index (length (scanner-text s)))
        (char (scanner-text s) index)
        #\Nul)))
(defun sc-check (s char &optional (k 0))
  (char= (sc-char s k) char))
(defun sc-mark (s)
  (make-mark (scanner-line s) (scanner-column s) (scanner-pos s)))
(defun sc-skip (s)
  (unless (sc-z-p s)
    (incf (scanner-pos s))
    (incf (scanner-column s)))
  nil)
(defun sc-skip-line (s)
  (when (sc-check s #\Return) (sc-skip s))
  (when (sc-check s #\Newline) (sc-skip s))
  (incf (scanner-line s))
  (setf (scanner-column s) 0)
  nil)
(defun sc-read (s buffer)
  (unless (sc-printable-p s)
    (sc-error s "while scanning YAML input" (sc-mark s)
              "found an unacceptable control character"))
  (vector-push-extend (sc-char s) buffer)
  (sc-skip s)
  buffer)
(defun sc-read-line (s buffer)
  (vector-push-extend #\Newline buffer)
  (sc-skip-line s)
  buffer)
(defun sc-hex-value (s k)
  (let ((code (char-code (sc-char s k))))
    (cond ((<= (char-code #\0) code (char-code #\9)) (- code (char-code #\0)))
          ((<= (char-code #\A) code (char-code #\F)) (+ 10 (- code (char-code #\A))))
          ((<= (char-code #\a) code (char-code #\f)) (+ 10 (- code (char-code #\a))))
          (t (sc-error s "while scanning a hexadecimal value" (sc-mark s)
                       "expected a hexadecimal digit")))))
(defun sc-error (s context context-mark problem)
  (declare (ignore s))
  (let ((mark context-mark))
    (error 'yaml-parse-error
         :line (mark-line mark)
         :column (mark-column mark)
         :offset (mark-offset mark)
         :context context
         :message problem)))
(defun make-scan-buffer ()
  (make-array 64 :element-type 'character :adjustable t :fill-pointer 0))
(defun scan-buffer-string (buffer)
  (let* ((length (fill-pointer buffer))
         (string (make-string length)))
    (replace string buffer :end2 length)
    string))
(defun enqueue-token (s token)
  (vector-push-extend token (scanner-tokens s))
  (setf (scanner-token-available s) t
        (scanner-json-like-node-end s) (token-ends-json-like-node-p token))
  token)
(defun insert-token (s index token)
  (let* ((tokens (scanner-tokens s))
         (absolute (+ (scanner-tokens-head s) index))
         (length (fill-pointer tokens)))
    (vector-push-extend nil tokens)
    (replace tokens tokens :start1 (1+ absolute) :start2 absolute :end2 length)
    (setf (aref tokens absolute) token
          (scanner-token-available s) t)
    token))
(defun insert-tokens (s index new-tokens)
  (let* ((tokens (scanner-tokens s))
         (absolute (+ (scanner-tokens-head s) index))
         (length (fill-pointer tokens))
         (count (length new-tokens)))
    (dotimes (i count) (vector-push-extend nil tokens))
    (replace tokens tokens :start1 (+ absolute count) :start2 absolute :end2 length)
    (loop for token in new-tokens
          for i from absolute
          do (setf (aref tokens i) token))
    (setf
          (scanner-token-available s) t)
    (car (last new-tokens))))
(defun make-scanner (text)
  (check-type text (simple-array character (*)))
  (let ((scanner (%make-scanner text)))
    (setf (scanner-simple-key-allowed scanner) t
          (scanner-simple-keys scanner) (list (make-simple-key)))
    scanner))
