;;;; src/scanner-scalars.lisp
(in-package #:yaml-kit)

(defun reader-hex-value (state count)
  (let ((value 0))
    (dotimes (unused count value)
      (declare (ignore unused))
      (let ((character (reader-peek state)))
        (unless (and character (digit-char-p character 16))
          (reader-parse-error state "invalid hexadecimal escape"))
        (setf value (+ (* value 16) (digit-char-p character 16)))
        (reader-advance state)))))

(defun reader-decode-double-quoted (state)
  (let ((out (make-array 32 :element-type 'character :adjustable t :fill-pointer 0)))
    (unless (char= (reader-peek state) #\") (reader-parse-error state "expected double quote"))
    (reader-advance state)
    (loop
      (when (reader-eof-p state) (reader-parse-error state "unterminated double-quoted scalar"))
      (let ((character (reader-peek state)))
        (cond
          ((char= character #\") (reader-advance state) (return (coerce out 'simple-string)))
          ((char= character #\\)
           (reader-advance state)
           (let ((escape (reader-peek state)))
             (when (null escape) (reader-parse-error state "unterminated escape"))
             (reader-advance state)
             (case escape
               (#\0 (vector-push-extend (code-char 0) out)) (#\a (vector-push-extend (code-char 7) out))
               (#\b (vector-push-extend (code-char 8) out)) (#\t (vector-push-extend #\Tab out))
               (#\n (vector-push-extend #\Newline out)) (#\v (vector-push-extend (code-char 11) out))
               (#\f (vector-push-extend (code-char 12) out)) (#\r (vector-push-extend #\Return out))
               (#\e (vector-push-extend (code-char 27) out)) (#\Space (vector-push-extend #\Space out))
               (#\" (vector-push-extend #\" out)) (#\/ (vector-push-extend #\/ out))
               (#\\ (vector-push-extend #\\ out)) (#\N (vector-push-extend (code-char #x85) out))
               (#\_ (vector-push-extend (code-char #xa0) out)) (#\L (vector-push-extend (code-char #x2028) out))
               (#\P (vector-push-extend (code-char #x2029) out))
               (#\x (vector-push-extend (code-char (reader-hex-value state 2)) out))
               (#\u (vector-push-extend (code-char (reader-hex-value state 4)) out))
               (#\U (vector-push-extend (code-char (reader-hex-value state 8)) out))
               (otherwise (reader-parse-error state "unknown escape")))))
          (t (vector-push-extend character out) (reader-advance state)))))))
