;;;; src/serializer.lisp
(in-package #:yaml-kit)

(defun %node-children (node)
  (cond ((sequence-node-p node) (sequence-node-items node))
        ((mapping-node-p node)
         (loop for pair in (mapping-node-pairs node)
               append (list (car pair) (cdr pair))))
        (t nil)))

(defun %assign-anchors (root)
  (let ((counts (make-hash-table :test #'eq))
        (seen (make-hash-table :test #'eq)))
    (labels ((count-node (node)
               (when (or (sequence-node-p node) (mapping-node-p node))
                 (incf (gethash node counts 0))
                 (unless (gethash node seen)
                   (setf (gethash node seen) t)
                   (dolist (child (%node-children node)) (count-node child))))))
      (count-node root)
      (clrhash seen)
      (let ((counter 0))
        (labels ((mark-node (node)
                   (when (or (sequence-node-p node) (mapping-node-p node))
                     (when (> (gethash node counts 0) 1)
                       (setf (node-anchor node)
                             (format nil "id~3,'0D" (incf counter))))
                     (unless (gethash node seen)
                       (setf (gethash node seen) t)
                       (dolist (child (%node-children node)) (mark-node child))))))
          (mark-node root)))))
  root)

(defun serialize (root handler &key (explicit-document-start nil))
  "Deliver serialized events to HANDLER in CPS order."
  (let ((active (make-hash-table :test #'eq))
        (emitted (make-hash-table :test #'eq)))
    (labels ((mark () (make-mark 0 0 0))
             (send (event) (funcall handler event))
             (alias (node)
               (send (make-alias-event :start-mark (mark) :end-mark (mark)
                                       :anchor (node-anchor node))))
             (walk (node)
               (when (gethash node emitted) (return-from walk (alias node)))
               (when (gethash node active) (return-from walk (alias node)))
               (when (or (sequence-node-p node) (mapping-node-p node))
                 (setf (gethash node active) t))
               (cond
                 ((scalar-node-p node)
                  (send (make-scalar-event :start-mark (mark) :end-mark (mark)
                                           :anchor (node-anchor node) :tag (node-tag node)
                                           :value (scalar-node-value node)
                                           :style (or (node-style node) :plain))))
                 ((sequence-node-p node)
                  (send (make-sequence-start-event :start-mark (mark) :end-mark (mark)
                                                   :anchor (node-anchor node) :tag (node-tag node)
                                                   :style (or (node-style node) :block)))
                  (dolist (child (sequence-node-items node)) (walk child))
                  (send (make-sequence-end-event :start-mark (mark) :end-mark (mark))))
                 ((mapping-node-p node)
                  (send (make-mapping-start-event :start-mark (mark) :end-mark (mark)
                                                  :anchor (node-anchor node) :tag (node-tag node)
                                                  :style (or (node-style node) :block)))
                  (dolist (pair (mapping-node-pairs node))
                    (walk (car pair)) (walk (cdr pair)))
                  (send (make-mapping-end-event :start-mark (mark) :end-mark (mark)))))
               (remhash node active)
               (when (or (sequence-node-p node) (mapping-node-p node))
                 (setf (gethash node emitted) t))))
      (%assign-anchors root)
      (send (make-stream-start-event :start-mark (mark) :end-mark (mark)))
      (send (make-document-start-event :start-mark (mark) :end-mark (mark)
                                       :explicit-p explicit-document-start))
      (walk root)
      (send (make-document-end-event :start-mark (mark) :end-mark (mark)))
      (send (make-stream-end-event :start-mark (mark) :end-mark (mark))))))
