name: Release
on:
  push:
    tags: ["v*.*.*"]
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: ./.github/actions/nix-setup
      - name: Verify tagged tree
        run: nix flake check --print-build-logs
